#define __STDC__ 1
#define __STDC_VERSION__ 199901L
#define __STDC_HOSTED__ 1
#define __STDC_ISO_10646__ 200607
#define __EDG__ 1
#define __EDG_VERSION__ 407
#define __EDG_SIZE_TYPE__ unsigned int
#define __EDG_PTRDIFF_TYPE__ int
#define __sizeof_int 4
#define __sizeof_long 4
#define __sizeof_ptr 4
#define __ARMCC_VERSION 5060750
#define __TARGET_CPU_CORTEX_M4_FP 1
#define __TARGET_FPU_VFPV4_SP_D16 1
#define __MICROLIB 1
#define __UVISION_VERSION 527
#define _RTE_ 1
#define STM32F407xx 1
#define USE_HAL_DRIVER 1
#define ROBOT_MODEL_INFANTRY 1
#define OLED_USE_SPI 1
#define USE_DEV_BOARD_C 1
#define __CC_ARM 1
#define __arm 1
#define __arm__ 1
#define __TARGET_ARCH_7E_M 1
#define __TARGET_ARCH_ARM 0
#define __TARGET_ARCH_THUMB 4
#define __TARGET_ARCH_A64 0
#define __TARGET_ARCH_AARCH32 1
#define __TARGET_PROFILE_M 1
#define __TARGET_FEATURE_HALFWORD 1
#define __TARGET_FEATURE_THUMB 1
#define __TARGET_FEATURE_MULTIPLY 1
#define __TARGET_FEATURE_DSPMUL 1
#define __TARGET_FEATURE_DOUBLEWORD 1
#define __TARGET_FEATURE_DIVIDE 1
#define __TARGET_FEATURE_UNALIGNED 1
#define __TARGET_FEATURE_CLZ 1
#define __TARGET_FEATURE_DMB 1
#define __TARGET_FPU_VFPV4 1
#define __TARGET_FPU_VFP 1
#define __TARGET_FPU_VFP_SINGLE 1
#define __TARGET_FEATURE_EXTENSION_REGISTER_COUNT 16
#define __APCS_INTERWORK 1
#define __FP_FAST_FMAF 1
#define __thumb 1
#define __thumb__ 1
#define __t32__ 1
#define __OPTIMISE_SPACE 1
#define __OPTIMISE_LEVEL 0
