"""生成入口头文件（xrobot.generate_main）：XR_REGISTER、实例、绑定、转换、诊断，
以及生成的 C++ 能否编译运行。
Generating the entry header (xrobot.generate_main): XR_REGISTER, instances, binding, conversions,
diagnostics, and whether the generated C++ compiles and runs.
"""

import os
import re
import stat
import unittest
from pathlib import Path

from fixtures import CXX, BspTestCase, CxxMixin, TempDirTestCase, TestCase, requires_cxx
from xr_syntax.cpp import code_tokens

from xrobot import config_edit
from xrobot.config import ConfigError
from xrobot.generate_main import (
    caller_defined_names,
    generate,
    generate_compile_check,
    load_modules,
    read_registrations,
    validate_all,
)
from xrobot.project import header_banner, read_header_inputs
from xrobot.type_index import TypeIndex


def led(identity="led", gpio="pin", param=None, gain="1.0f"):
    """一个 Led 实例的配置数据。
    The configuration data of one Led instance.
    """
    return {
        "module": "Led",
        "id": identity,
        "args": [
            {"gpio": gpio},
            {"param": param or {"cycle": "250", "inverted": "false"}},
            {"gain": gain},
        ],
    }


PROBE = """#include "Led.hpp"
class Probe {
 public:
  Probe(Port& port, Port* optional, int count = 1, const char* name = "probe") {}
};"""
LED = """namespace LibXR { class GPIO; class UART; }
struct Port { int value = 1; };
struct SubPort : Port {};
struct Hidden : private Port {};
class Led {
 public:
  struct Param { int cycle = 250; bool inverted{}; };
  Led(LibXR::GPIO& gpio, Param param = {}, float gain = 1.0f) {}
  void OnMonitor() {}
};"""


def probe(identity="probe", port="port", optional="nullptr", count="1", name='"probe"'):
    """一个 Probe 实例的配置数据。
    The configuration data of one Probe instance.
    """
    return {
        "module": "Probe",
        "id": identity,
        "args": [{"port": port}, {"optional": optional}, {"count": count}, {"name": name}],
    }


MAIN = '#include "xrobot_main.hpp"\nint main() { XROBOT_MAIN(); }\n'
CMD = """#include "Led.hpp"
class Cmd {
 public:
  explicit Cmd(Led& led, Led* backup) {}
  void OnMonitor() const noexcept {}
};"""
REGISTERED = (
    '#include "xrobot_main.hpp"\nint main() {\n'
    "  XR_REGISTER(pin, LibXR::GPIO);\n  XR_REGISTER(uart, LibXR::UART);\n"
    "  XR_REGISTER(port, Port);\n  XR_REGISTER(sub, SubPort);\n"
    "  XR_REGISTER(hidden, Hidden);\n  XR_REGISTER(unused, int);\n  XROBOT_MAIN();\n}\n"
)


class GenerationTestCase(BspTestCase):
    """带常用模块的 BSP，以及生成和取报错的辅助。
    A BSP with common Modules, and helpers that generate and collect errors.
    """

    def setUp(self):
        super().setUp()
        self.module("Led", LED)
        self.module("Probe", PROBE)
        self.module("Cmd", CMD)
        self.entry(REGISTERED)

    def code(self, *instances, **top):
        """用这些实例生成头文件并返回其文本。
        Generate the header with these instances and return its text.
        """
        top["modules"] = list(instances)
        return self.generate(top)

    def error(self, *instances, **top):
        """用这些实例生成头文件，返回报错文本。
        Generate the header with these instances and return the error text.
        """
        top["modules"] = list(instances)
        with self.assertRaises(ValueError) as context:
            self.generate(top)
        return str(context.exception)


class HeaderShape(GenerationTestCase):
    """生成头文件的结构。
    The structure of the generated header.
    """

    def test_the_complete_header_of_one_instance(self):
        code = self.code(
            led(),
            constexprs={"Rate": {"type": "int", "value": "1000"}},
            settings={"monitor_sleep_ms": "5"},
        )
        digest = read_header_inputs(self.root / "User/xrobot_main.hpp").digest
        self.assertEqual(
            code,
            f"""// Generated by `xrobot gen` from User/xrobot.yaml; do not edit by hand.
#pragma once

#include "Led.hpp"
#include "libxr.hpp"
#include "thread.hpp"

namespace ProjectConstexpr
{{
inline constexpr int Rate = 1000;
}}  // namespace ProjectConstexpr

[[noreturn]] static inline void XRobotMain(LibXR::GPIO& pin)
{{
  // led: team/Led (xrobot.yaml:8)
#line 8 "xrobot.yaml"
  static const Led::Param xr_led_param = {{
      .cycle = 250,
      .inverted = false,
  }};
  static Led led(pin, xr_led_param, 1.0f);
#line 23 "xrobot_main.hpp"

  for (;;)
  {{
    led.OnMonitor();
    LibXR::Thread::Sleep(5);
  }}
}}

// XR_REGISTER marks a name for the generator; XRobotMain binds and type-checks it.
#define XR_REGISTER(name, ...) static_cast<void>(name)
#define XROBOT_MAIN() ::XRobotMain(pin)

// xrobot: config "xrobot.yaml"
// xrobot: depends "../xrobot.lock"
// xrobot: entry "app_main.cpp"
// xrobot: depends "../Modules/team/Cmd/Cmd.hpp"
// xrobot: depends "../Modules/team/Led/Led.hpp"
// xrobot: depends "../Modules/team/Probe/Probe.hpp"
// xrobot: digest {digest}
""",
        )

    def test_the_banner_names_the_config_and_the_input_list_ends_the_file(self):
        lines = self.code(led()).split("\n")
        self.assertEqual(lines[:2], [header_banner("User/xrobot.yaml"), "#pragma once"])
        self.assertEqual(lines[-8], '// xrobot: config "xrobot.yaml"')
        self.assertTrue(lines[-2].startswith("// xrobot: digest "))
        self.assertEqual(lines[-1], "")
        self.assertEqual(self.project.header_selection(), self.root / "User/xrobot.yaml")
        self.assertEqual(self.project.header_state()["status"], "fresh")

    def test_a_long_banner_is_wrapped_into_comment_lines_within_the_column_limit(self):
        name = "products/" + "x" * 40 + ".yaml"
        self.generate({"modules": [led()]}, name=name)
        lines = self.read("User/xrobot_main.hpp").split("\n")
        banner = lines[: lines.index("#pragma once")]
        self.assertEqual(len(banner), 2)
        self.assertTrue(all(len(line) <= 90 and line.startswith("// ") for line in banner))
        self.assertEqual(
            " ".join(line[3:] for line in banner),
            f"Generated by `xrobot gen` from User/{name}; do not edit by hand.",
        )

    def test_each_instance_has_a_comment_with_its_module_and_yaml_line(self):
        self.module(
            "Buf",
            "template <typename T, unsigned N = 4>\n"
            "class Buf { public: explicit Buf(T init = T{}) {} };",
        )
        config = self.config(
            "modules:\n  - module: Led\n    id: led\n    args:\n      - gpio: pin\n"
            "      - param: {cycle: 1, inverted: false}\n      - gain: 1.0f\n"
            "  - module: Buf\n    id: buf\n    template_args:\n      - float\n      - 8\n"
            "    args:\n      - init: 2.0f\n"
        )
        code = generate(self.project, config)
        self.assertIn("\n  // led: team/Led (xrobot.yaml:2)\n", code)
        self.assertIn("\n  // buf: team/Buf<float, 8> (xrobot.yaml:8)\n", code)
        # 实例之间空一行。
        # One blank line between instances.
        self.assertRegex(code, r"\n#line \d+ \"xrobot_main\.hpp\"\n\n  // buf: ")

    def test_types_from_included_module_headers_are_checked_and_tracked(self):
        self.module(
            "Bar",
            '#include "detail/Config.hpp"\nclass Bar { public:\n'
            "  explicit Bar(DetailConfig config = {}) { (void)config; } };",
            extra_headers={"detail/Config.hpp": "#pragma once\nstruct DetailConfig { int rate; };"},
        )
        code = self.code({"module": "Bar", "id": "bar", "args": [{"config": {"rate": "200"}}]})
        self.assertIn(".rate = 200", code)
        self.assertIn('// xrobot: depends "../Modules/team/Bar/detail/Config.hpp"', code)
        message = self.error({"module": "Bar", "id": "bar", "args": [{"config": {"speed": "1"}}]})
        self.assertIn("bar.args.config: missing rate; unknown speed", message)

    def test_entry_function_takes_only_consumed_registrations(self):
        code = self.code(led())
        self.assertIn("[[noreturn]] static inline void XRobotMain(LibXR::GPIO& pin)\n{", code)
        self.assertIn("\n#define XROBOT_MAIN() ::XRobotMain(pin)\n", code)
        for name in ("uart", "unused", "hidden", "port"):
            self.assertNotRegex(code, rf"\b{name}\b")

    def many_registrations(self, count):
        """一个用到 count 个注册的配置生成的头文件文本。
        The header of a configuration that uses count registrations.
        """
        names = [f"gpio_{i}" for i in range(count)]
        self.entry(
            '#include "xrobot_main.hpp"\nint main() {\n'
            + "".join(f"  XR_REGISTER({name}, LibXR::GPIO);\n" for name in names)
            + "  XROBOT_MAIN();\n}\n"
        )
        return self.code(*[led(f"led_{i}", gpio=name) for i, name in enumerate(names)])

    def test_a_long_entry_function_aligns_its_parameters_after_the_parenthesis(self):
        code = self.many_registrations(14)
        indent = " " * 43
        self.assertIn(
            "[[noreturn]] static inline void XRobotMain(LibXR::GPIO& gpio_0, LibXR::GPIO& gpio_1,\n"
            + indent
            + "LibXR::GPIO& gpio_2, LibXR::GPIO& gpio_3,\n",
            code,
        )
        self.assertIn(indent + "LibXR::GPIO& gpio_12, LibXR::GPIO& gpio_13)\n{\n", code)

    def test_a_very_long_entry_function_breaks_after_the_parenthesis(self):
        code = self.many_registrations(30)
        self.assertIn(
            "[[noreturn]] static inline void XRobotMain(\n"
            "    LibXR::GPIO& gpio_0, LibXR::GPIO& gpio_1, LibXR::GPIO& gpio_2, "
            "LibXR::GPIO& gpio_3,\n",
            code,
        )
        self.assertIn("LibXR::GPIO& gpio_29)\n{\n", code)

    def test_a_long_macro_wraps_at_the_column_limit_with_aligned_continuations(self):
        code = self.many_registrations(14)
        macro = code[code.index("#define XROBOT_MAIN()") :].split("\n\n")[0].split("\n")
        self.assertEqual(macro[0].split()[:2], ["#define", "XROBOT_MAIN()"])
        self.assertTrue(macro[1].startswith("  ::XRobotMain(gpio_0, gpio_1, "))
        self.assertTrue(macro[-1].endswith("gpio_13)"))
        # 续行符对齐在同一列，每行不超过 90 个字符。
        # The line continuations share one column, and no line is longer than 90 characters.
        self.assertEqual({len(line) for line in macro[:-1]}, {len(macro[0])})
        for line in code.split("\n"):
            if not line.startswith("// xrobot:"):
                self.assertLessEqual(len(line), 90, line)

    def test_register_macro_expands_to_nothing(self):
        code = self.code(led())
        self.assertIn("\n#define XR_REGISTER(name, ...) static_cast<void>(name)\n", code)
        self.assertNotIn("XR_REGISTER_DETAIL", code)
        self.assertNotRegex(code, r"static_assert\([^;]*\bpin\b")

    def test_no_instances_give_a_parameterless_entry_that_still_sleeps(self):
        code = self.code()
        self.assertIn("[[noreturn]] static inline void XRobotMain()\n{\n  for (;;)\n", code)
        self.assertIn("#define XROBOT_MAIN() ::XRobotMain()\n", code)
        self.assertIn("    LibXR::Thread::Sleep(1000);", code)

    def test_one_sorted_include_block_holds_the_modules_and_what_the_code_needs(self):
        code = self.code(
            led(), constexpr_includes=["Board.hpp", "<vector>", "sub/Pins.h", "<stdint.h>"]
        )
        start = code.index("#pragma once\n\n") + len("#pragma once\n\n")
        block = code[start:].split("\n\n[[noreturn]]")[0]
        # 与 clang-format 的 IncludeBlocks: Regroup 一致：<*.h>、其他 <…>、"…" 各一组，组内排序。
        # As clang-format's IncludeBlocks: Regroup: <*.h>, other <...> and "..." in groups,
        # each sorted.
        self.assertEqual(
            block,
            "#include <stdint.h>\n\n#include <vector>\n\n"
            '#include "Board.hpp"\n#include "Led.hpp"\n#include "libxr.hpp"\n'
            '#include "sub/Pins.h"\n#include "thread.hpp"',
        )

    def test_only_the_standard_headers_the_code_uses_are_included(self):
        self.module(
            "Store",
            "#include <initializer_list>\nclass Store { public:\n"
            "  Store(std::initializer_list<int> values = {1}) {} };",
        )
        plain = self.code(led())
        self.assertNotIn("#include <", plain)
        code = self.code(
            {"module": "Store", "id": "store", "args": [{"values": ["3", "4"]}]},
            probe(optional="port"),
        )
        self.assertIn("#include <initializer_list>\n#include <memory>\n\n", code)
        self.assertNotIn("<utility>", code)

    def test_constexprs_are_emitted_in_their_namespace_before_the_entry(self):
        code = self.code(
            led(param={"cycle": "Board::Rate", "inverted": "false"}),
            constexpr_namespace="Board",
            constexprs={
                "Rate": {"type": "int", "value": "250"},
                "Gains": {"type": "std::array<float, 2>", "value": "{1.0F, 2.0F}"},
            },
        )
        self.assertIn(
            "namespace Board\n{\ninline constexpr int Rate = 250;\n"
            "inline constexpr std::array<float, 2> Gains{1.0F, 2.0F};\n"
            "}  // namespace Board\n",
            code,
        )
        self.assertLess(code.index("inline constexpr int Rate"), code.index("void XRobotMain("))
        self.assertIn(".cycle = Board::Rate", code)

    def test_a_struct_constant_has_one_field_per_line(self):
        self.module(
            "Cfg",
            "struct CfgParam { int a; float b; };\n"
            "class Cfg { public: explicit Cfg(CfgParam p = {}) {} };",
        )
        code = self.code(
            constexprs={"Limits": {"type": "CfgParam", "value": {"a": "1", "b": "2.0F"}}}
        )
        self.assertIn("inline constexpr CfgParam Limits{\n    .a = 1,\n    .b = 2.0F,\n};\n", code)

    def test_constexpr_errors_are_reported(self):
        message = self.error(constexprs={"Rate": {"type": "int", "value": None}})
        self.assertRegex(message, r"xrobot\.yaml: constexprs\.Rate(\.value)? is not filled in")

    def test_monitor_sleep_is_taken_from_settings(self):
        self.assertIn("LibXR::Thread::Sleep(20);", self.code(settings={"monitor_sleep_ms": "20"}))

    def test_instances_are_function_local_statics_in_yaml_order(self):
        code = self.code(led("b_led"), led("a_led"), probe())
        order = [m.group(1) for m in re.finditer(r"^  static \w+ (\w+)\(", code, re.M)]
        self.assertEqual(order, ["b_led", "a_led", "probe"])

    def test_monitors_are_called_in_yaml_order_without_assertions_for_a_known_void_result(self):
        code = self.code(
            led("first"),
            {"module": "Cmd", "id": "cmd", "args": [{"led": "first"}, {"backup": "nullptr"}]},
            probe(),
            led("last"),
        )
        loop = code[code.index("for (;;)") :]
        self.assertEqual(re.findall(r"(\w+)\.OnMonitor\(\);", loop), ["first", "cmd", "last"])
        self.assertNotIn("static_assert", code)
        self.assertNotIn("probe.OnMonitor", code)


class LineDirectives(GenerationTestCase):
    """把实例映射回配置的 #line 指令。
    The #line directives that map instances back to the configuration.
    """

    CONFIG = (
        "# robot\nmodules:\n  - module: Led\n    id: led\n    args:\n      - gpio: pin\n"
        "      - param:\n          cycle: 100\n          inverted: true\n"
        "      - gain: 2.5F\n  - module: Probe\n    id: probe\n    args:\n"
        "      - port: sub\n      - optional: '&port'\n      - count: 2\n"
        '      - name: "p"\n'
    )

    def test_one_directive_per_instance_points_into_the_yaml_and_one_back_into_the_header(self):
        config = self.config(self.CONFIG)
        code = generate(self.project, config)
        lines = code.split("\n")
        into, back = [], []
        for number, line in enumerate(lines, 1):
            if match := re.fullmatch(r'#line (\d+) "xrobot\.yaml"', line):
                into.append((int(match.group(1)), lines[number]))
            elif match := re.fullmatch(r'#line (\d+) "xrobot_main\.hpp"', line):
                # 指回头文件的指令写的是下一行的行号。
                # A directive back into the header names the number of the next line.
                self.assertEqual(int(match.group(1)), number + 1)
                back.append(number)
        # 语句（包括实例前的 static 变量）紧跟在指向这个实例的指令之后。
        # The statements, static variables before the instance included, follow the directive
        # of their instance.
        self.assertEqual(
            into,
            [
                (3, "  static const Led::Param xr_led_param = {"),
                (11, '  static Probe probe(sub, &port, 2, "p");'),
            ],
        )
        self.assertEqual(len(back), 2)
        for number in back:
            self.assertEqual(lines[number], "")

    def test_paths_are_relative_to_the_header(self):
        self.config(self.CONFIG, name="products/hero.yaml")
        code = generate(self.project, self.root / "User/products/hero.yaml")
        self.assertIn('\n#line 3 "products/hero.yaml"\n', code)
        self.assertIn("(products/hero.yaml:3)", code)
        self.assertNotIn(self.root.as_posix(), code)
        self.assertNotRegex(code, r'#line \d+ "(/|[A-Za-z]:)')

    def test_the_directives_can_be_left_out(self):
        config = self.config(self.CONFIG)
        with_directives = generate(self.project, config)
        without = generate(self.project, config, line_directives=False)
        self.assertNotIn("#line", without)
        self.assertEqual(
            without,
            "\n".join(line for line in with_directives.split("\n") if not line.startswith("#line")),
        )

    def test_the_compile_check_probe_has_no_line_directives(self):
        out = self.tmp / "check.cpp"
        code = generate_compile_check("team/Probe", load_modules(self.project), out)
        self.assertNotIn("#line", code)


class Conversions(GenerationTestCase):
    """值到参数类型的转换：C++ 自己检查，只有选定构造函数需要时才写出类型。
    Conversions of values to parameter types: C++ checks them itself, and a type is written
    only when it is needed to select the constructor.
    """

    def test_scalar_values_are_written_as_they_are(self):
        code = self.code(led(gain="2"), probe(count="3"))
        self.assertIn("static Led led(pin, xr_led_param, 2);", code)
        self.assertIn('static Probe probe(port, nullptr, 3, "probe");', code)
        instances = code.split("#define XR_REGISTER")[0]
        for construct in ("Implicit", "static_cast", "static_assert"):
            self.assertNotIn(construct, instances)

    def test_a_registration_of_the_parameter_type_binds_directly(self):
        self.assertIn("static Probe probe(port, ", self.code(probe(port="port")))

    def test_a_derived_registration_binds_through_the_implicit_conversion(self):
        code = self.code(probe(port="sub"))
        self.assertIn("static Probe probe(sub, ", code)
        self.assertNotIn("static_cast<Port&>", code)

    def test_a_bare_name_for_a_pointer_parameter_passes_its_address(self):
        code = self.code(probe(optional="port"))
        self.assertIn("static Probe probe(port, std::addressof(port), ", code)
        self.assertIn("#include <memory>", code)
        self.assertIn(
            "static Probe probe(port, std::addressof(sub), ", self.code(probe(optional="sub"))
        )

    def test_address_of_and_nullptr_are_accepted_for_pointers(self):
        self.assertIn("static Probe probe(port, &port, ", self.code(probe(optional="&port")))
        self.assertIn("static Probe probe(port, nullptr, ", self.code(probe(optional="nullptr")))

    def test_an_earlier_instance_binds_like_a_registration(self):
        code = self.code(
            led(), {"module": "Cmd", "id": "cmd", "args": [{"led": "led"}, {"backup": "&led"}]}
        )
        self.assertIn("static Cmd cmd(led, &led);", code)

    def test_values_of_reference_and_initializer_list_parameters_get_static_storage(self):
        self.module(
            "Store",
            "#include <initializer_list>\nclass Store { public:\n"
            "  struct Param { int a; };\n"
            "  Store(const Param& p = {.a = 1}, std::initializer_list<int> values = {1, 2}) {} };",
        )
        code = self.code(
            {"module": "Store", "id": "store", "args": [{"p": {"a": "2"}}, {"values": ["3", "4"]}]}
        )
        # 紧邻实例之前，名字是 xr_<实例>_<参数>，和实例一样活到程序结束。
        # Right before the instance, named xr_<instance>_<parameter>, and as long-lived as it.
        self.assertIn(
            "  static const Store::Param xr_store_p = {\n      .a = 2,\n  };\n"
            "  static const std::initializer_list<int> xr_store_values = {3, 4};\n"
            "  static Store store(xr_store_p, xr_store_values);\n",
            code,
        )

    def test_a_struct_passed_by_value_gets_static_storage_too(self):
        self.module(
            "Pair",
            "class Pair { public:\n  struct Param { int a; int b; };\n"
            "  Pair(Param param, int n = 1) {} };",
        )
        code = self.code(
            {
                "module": "Pair",
                "id": "pair",
                "args": [{"param": {"a": "1", "b": "2"}}, {"n": "5"}],
            }
        )
        self.assertIn(
            "  static const Pair::Param xr_pair_param = {\n      .a = 1,\n      .b = 2,\n  };\n"
            "  static Pair pair(xr_pair_param, 5);\n",
            code,
        )

    def test_a_name_or_expression_for_a_reference_refers_to_the_object_itself(self):
        # 名字和表达式不是配置新建的对象：按引用绑定，既不复制，也延长临时对象的生存期。
        # A name or expression is not an object the configuration creates: it binds by
        # reference, which neither copies it nor leaves a temporary behind.
        self.module(
            "Hold",
            "struct Config { int v = 1; };\n"
            "class Hold { public:\n  static Config Make() { return {}; }\n"
            "  Hold(const Config& config = Make()) {} };",
        )
        for value in ("shared", "Hold::Make()", "Config()"):
            with self.subTest(value=value):
                code = self.code(
                    {"module": "Hold", "id": "hold", "args": [{"config": value}]},
                )
                self.assertIn(
                    f"  static const Config& xr_hold_config = {value};\n"
                    "  static Hold hold(xr_hold_config);\n",
                    code,
                )

    def test_an_rvalue_reference_parameter_moves_its_static_object(self):
        self.module(
            "Sink",
            "class Sink { public:\n  struct Param { int a; };\n  Sink(Param&& p = {}) {} };",
        )
        code = self.code({"module": "Sink", "id": "sink", "args": [{"p": {"a": "1"}}]})
        self.assertIn(
            "  static Sink::Param xr_sink_p = {\n      .a = 1,\n  };\n"
            "  static Sink sink(std::move(xr_sink_p));\n",
            code,
        )
        self.assertIn("#include <utility>", code)

    def test_a_storage_name_two_instances_would_share_is_reported(self):
        self.module(
            "One", "class One { public:\n  struct P { int a; };\n  One(const P& b_c = {}) {} };"
        )
        self.module(
            "Two", "class Two { public:\n  struct P { int a; };\n  Two(const P& c = {}) {} };"
        )
        message = self.error(
            {"module": "One", "id": "a", "args": [{"b_c": {"a": "1"}}]},
            {"module": "Two", "id": "a_b", "args": [{"c": {"a": "2"}}]},
        )
        self.assertEqual(
            message,
            "User/xrobot.yaml: a_b.args.c and a.args.b_c would both be stored as xr_a_b_c; "
            "rename one of the instance ids",
        )

    def test_a_constructor_chosen_among_several_converts_values_to_its_parameters(self):
        self.module(
            "Pick",
            '#include "Led.hpp"\nclass Pick { public:\n'
            "  Pick(Port& port, int n = 1) {}\n  Pick(Led& led, int n = 1) {} };",
        )
        code = self.code(
            {"module": "Pick", "id": "pick", "args": [{"port": "sub"}, {"n": "2"}]},
        )
        # 同名参数数的构造函数不止一个：隐式转换选定 YAML 写的那一个，同时仍拒绝向下转换。
        # Several constructors could take the call: an implicit conversion selects the one the
        # YAML names, and downcasts stay rejected.
        self.assertIn(
            "  static Pick pick(xrobot_generated::Implicit<Port&>(sub),\n"
            "                   xrobot_generated::Implicit<int>(2));\n",
            code,
        )
        self.assertIn("namespace xrobot_generated\n{\n", code)
        self.assertIn("#include <type_traits>\n", code)
        self.assertNotIn("static_assert", code)
        self.assertNotIn("xrobot_generated", self.code(led()))


class Dependencies(GenerationTestCase):
    """依赖参数的绑定。
    Binding dependency parameters.
    """

    def test_unknown_name_lists_candidates_of_the_parameter_type(self):
        message = self.error(probe(port="missing"))
        # sub 是 SubPort（公有基类 Port）；hidden 私有继承，不能绑定。
        # sub is a SubPort (public base Port); hidden derives privately and does not bind.
        self.assertIn(
            "xrobot.yaml: probe.args.port: missing is neither an XR_REGISTER name nor an earlier "
            "instance id; candidates of type Port&: port, sub\n",
            message + "\n",
        )

    def test_unknown_address_for_a_pointer_is_rejected(self):
        self.assertIn(
            "probe.args.optional: missing is neither an XR_REGISTER name nor an earlier instance "
            "id; candidates of type Port*: &port, &sub, nullptr\n",
            self.error(probe(optional="&missing")) + "\n",
        )

    def test_self_and_later_instances_are_rejected(self):
        message = self.error(
            {"module": "Cmd", "id": "cmd", "args": [{"led": "led"}, {"backup": "&cmd"}]}, led()
        )
        self.assertIn(
            "cmd.args.led: led is constructed after cmd; instances are constructed in list order",
            message,
        )
        self.assertIn("cmd.args.backup refers to cmd itself", message)

    def test_a_located_type_without_a_public_base_relation_is_rejected(self):
        message = self.error(probe(port="hidden"))
        self.assertIn(
            "probe.args.port: hidden is a Hidden, which does not convert to Port&", message
        )
        message = self.error(
            led(), {"module": "Cmd", "id": "cmd", "args": [{"led": "port"}, {"backup": "nullptr"}]}
        )
        self.assertIn("cmd.args.led: port is a Port, which does not convert to Led&", message)

    def test_a_located_pointer_without_a_public_base_relation_is_rejected(self):
        for value in ("&hidden", "hidden"):
            with self.subTest(value=value):
                self.assertIn(
                    "probe.args.optional: hidden is a Hidden, which does not convert to Port*",
                    self.error(probe(optional=value)),
                )

    def test_types_the_index_cannot_locate_are_left_to_the_compiler(self):
        self.code(led(gpio="uart"))

    def test_an_instance_with_errors_is_not_offered_to_later_instances(self):
        message = self.error(
            led(gpio="missing"),
            {"module": "Cmd", "id": "cmd", "args": [{"led": "led"}, {"backup": "nullptr"}]},
        )
        self.assertIn("led.args.gpio: missing is neither", message)
        self.assertIn("cmd.args.led: led has errors of its own", message)


class Names(GenerationTestCase):
    """实例 id、登记名和模块名的冲突。
    Conflicts between instance ids, registration names and Module names.
    """

    def test_instance_id_equal_to_a_module_class_name_is_rejected(self):
        for identity in ("Led", "Port", "SubPort"):
            with self.subTest(identity=identity):
                self.assertIn(
                    f"instance id {identity} is also a class name in the loaded Modules",
                    self.error(led(identity)),
                )

    def test_instance_id_equal_to_a_registration_is_rejected(self):
        self.assertIn("instance id port is also an XR_REGISTER name", self.error(led("port")))

    def test_registration_named_like_a_module_class_is_rejected(self):
        self.entry(
            '#include "xrobot_main.hpp"\nint main() { XR_REGISTER(Port, Port); XROBOT_MAIN(); }\n'
        )
        self.assertIn("XR_REGISTER name Port is also a Module class name", self.error())

    def test_unknown_and_ambiguous_module_names(self):
        self.assertIn("Module not found: Missing", self.error({"module": "Missing", "id": "m"}))
        self.module("Led", "class Led { public: Led() {} };", owner="other")
        self.assertIn("Ambiguous Module Led; specify", self.error({"module": "Led", "id": "m"}))
        first = led()
        first["module"] = "team/Led"
        self.assertIn(
            "b: team/Led and other/Led both define the global class Led; use only one of them",
            self.error(first, {"module": "other/Led", "id": "b"}),
        )

    def test_non_standalone_modules_cannot_be_instantiated(self):
        self.module(
            "Base",
            "class Base { public: Base() {} };",
            manifest="/* === MODULE MANIFEST V2 ===\n"
            "module_description: library\nstandalone: false\n=== END MANIFEST === */\n",
        )
        self.assertIn(
            "team/Base is a library (standalone: false) and cannot be instantiated",
            self.error({"module": "Base", "id": "b"}),
        )

    def test_unmatched_argument_names_list_the_constructors(self):
        message = self.error(
            {"module": "Probe", "id": "p", "args": [{"port": "port"}, {"opt": "nullptr"}]}
        )
        self.assertIn(
            "named arguments (port, opt) do not match any constructor of Probe; expected one of: "
            "(port, optional, count, name)",
            message,
        )


class Diagnostics(GenerationTestCase):
    """报错的收集方式，以及失败时保留旧的头文件。
    How errors are collected, and that a failure keeps the previous header.
    """

    def test_errors_of_every_instance_are_collected_with_config_and_path_prefixes(self):
        # 依赖参数没有填写或名字不对时都列出候选（以前没有填写时不列）；没有候选时写 none。
        # A dependency that is not filled in or names something wrong lists its candidates
        # (an unfilled one used to list none), and "none" when there is no candidate.
        self.module(
            "Lonely", "struct Alone {};\nclass Lonely { public: explicit Lonely(Alone& alone) {} };"
        )
        message = self.error(
            probe("a", port="missing"),
            led("b", gpio=None),
            probe("c", optional=None),
            {"module": "Lonely", "id": "d", "args": [{"alone": None}]},
            {"module": "Lonely", "id": "e", "args": [{"alone": "nobody"}]},
            led("Led"),
        )
        self.assertEqual(
            message,
            "User/xrobot.yaml: a.args.port: missing is neither an XR_REGISTER name nor an earlier "
            "instance id; candidates of type Port&: port, sub\n"
            "User/xrobot.yaml: b.args.gpio is not filled in; candidates of type LibXR::GPIO&: pin\n"
            "User/xrobot.yaml: c.args.optional is not filled in; candidates of type Port*: &port, "
            "&sub, nullptr\n"
            "User/xrobot.yaml: d.args.alone is not filled in; candidates of type Alone&: none\n"
            "User/xrobot.yaml: e.args.alone: nobody is neither an XR_REGISTER name nor an earlier "
            "instance id; candidates of type Alone&: none\n"
            "User/xrobot.yaml: Led: instance id Led is also a class name in the loaded Modules; "
            "use a lower-case id such as led",
        )

    def test_structural_errors_name_the_config_file(self):
        with self.assertRaisesMessage(
            ConfigError, "User/xrobot.yaml: modules[0]: unknown key(s) extra"
        ):
            self.generate({"modules": [{"module": "Led", "id": "led", "extra": "x"}]})

    def test_a_failed_generation_leaves_the_previous_header(self):
        self.code(led())
        header = self.root / "User/xrobot_main.hpp"
        before = header.read_bytes()
        self.error(probe(port="missing"))
        self.assertEqual(header.read_bytes(), before)

    @unittest.skipIf(os.name == "nt", "POSIX permission bits")
    def test_regeneration_keeps_the_header_permission_bits(self):
        self.code(led())
        header = self.root / "User/xrobot_main.hpp"
        header.chmod(0o640)
        self.code(led(), probe())
        self.assertEqual(stat.S_IMODE(header.stat().st_mode), 0o640)

    @unittest.skipIf(os.name == "nt", "POSIX permission bits")
    def test_a_new_header_follows_the_umask(self):
        umask = os.umask(0o022)
        try:
            self.code(led())
        finally:
            os.umask(umask)
        self.assertEqual(stat.S_IMODE((self.root / "User/xrobot_main.hpp").stat().st_mode), 0o644)


class Selection(GenerationTestCase):
    """生成哪一份配置。
    Which configuration is generated.
    """

    def test_generate_uses_the_selected_product_by_default(self):
        self.config({"modules": [led("default_led")]})
        self.config({"modules": [led("alt_led")]}, name="alt.yaml")
        self.assertIn("default_led", generate(self.project))
        self.assertIn("alt_led", generate(self.project, self.root / "User/alt.yaml"))
        self.assertIn("alt_led", generate(self.project))

    def test_a_missing_config_is_reported(self):
        with self.assertRaisesMessage(ConfigError, "User/missing.yaml does not exist"):
            generate(self.project, self.root / "User/missing.yaml")

    def test_validate_all_checks_every_config_and_collects_errors(self):
        self.config({"modules": [led()]})
        self.config({"modules": [probe(port="missing")]}, name="products/a.yaml")
        self.config({"modules": [led("Led")]}, name="products/b.yaml")
        with self.assertRaises(ConfigError) as context:
            validate_all(self.project)
        message = str(context.exception)
        self.assertIn("User/products/a.yaml: probe.args.port: missing is neither", message)
        self.assertIn("User/products/b.yaml: Led: instance id Led is also a class name", message)
        self.assertNotIn("User/xrobot.yaml", message)
        (self.root / "User/products/a.yaml").unlink()
        (self.root / "User/products/b.yaml").unlink()
        self.assertEqual(validate_all(self.project), 1)
        self.assertFalse((self.root / "User/xrobot_main.hpp").exists())


class Monitors(BspTestCase):
    """生成的主循环调用哪些 OnMonitor。
    Which OnMonitor functions the generated main loop calls.
    """

    def setUp(self):
        super().setUp()
        self.entry(MAIN)

    def monitored(self, body, name="M"):
        """生成的主循环是否调用这个类的 OnMonitor。
        Whether the generated main loop calls OnMonitor of this class.
        """
        self.module(name, body)
        code = self.generate({"modules": [{"module": name, "id": "m"}]})
        return "m.OnMonitor();" in code

    def test_a_public_monitor_is_called(self):
        self.assertTrue(self.monitored("class M { public: M() {} void OnMonitor() {} };"))

    def test_calling_a_members_monitor_does_not_make_the_class_monitored(self):
        # 成员函数里调用成员的 OnMonitor() 不等于类自己声明了 OnMonitor：循环不会调用它，
        # 也不会为它写 static_assert。
        # Calling the OnMonitor() of a member inside a member function does not mean the class
        # declares OnMonitor: the loop does not call it and no static_assert is written.
        self.module("Sensor", "class Sensor { public: Sensor() {} void OnMonitor() {} };")
        calling = (
            '#include "Sensor.hpp"\nclass M { public: M() {}\n'
            "  void Update() { sensor_.OnMonitor(); }\n private:\n  Sensor sensor_;\n};"
        )
        self.assertFalse(self.monitored(calling))
        declaring = calling.replace("void Update()", "void OnMonitor()")
        self.assertTrue(self.monitored(declaring))
        self.assertNotIn("static_assert", self.generate({"modules": [{"module": "M", "id": "m"}]}))

    def test_a_private_or_missing_monitor_is_not_called(self):
        self.assertFalse(self.monitored("class M { public: M() {} private: void OnMonitor() {} };"))
        self.assertFalse(self.monitored("class M { public: M() {} };"))

    def test_a_monitor_inherited_from_a_module_base_is_called(self):
        self.assertTrue(
            self.monitored(
                "struct Core { void OnMonitor() {} };\nclass M : public Core { public: M() {} };"
            )
        )
        self.assertFalse(
            self.monitored(
                "struct Core { void OnMonitor() {} };\nclass M : Core { public: M() {} };"
            )
        )

    def test_an_unlocatable_public_base_is_an_error(self):
        self.module("M", "class M : public Vendor::Base { public: M() {} };")
        with self.assertRaisesMessage(
            ConfigError,
            "User/xrobot.yaml: m: cannot tell whether a public base class provides OnMonitor; "
            "its base is not defined in the loaded Module headers",
        ):
            self.generate({"modules": [{"module": "M", "id": "m"}]})

    def test_a_conditional_monitor_is_an_error(self):
        self.module("M", "class M { public: M() {}\n#if FEATURE\n  void OnMonitor() {}\n#endif\n};")
        with self.assertRaisesMessage(
            ValueError,
            "User/xrobot.yaml: m: M declares OnMonitor under #if; the generator cannot "
            "evaluate build options",
        ):
            self.generate({"modules": [{"module": "M", "id": "m"}]})

    def test_a_result_that_is_certainly_not_void_is_an_error_at_generation(self):
        for returned in ("int", "bool", "unsigned long", "std::uint8_t", "void*", "const char*"):
            with self.subTest(returned=returned):
                self.module(
                    "M",
                    "#include <cstdint>\nclass M { public: M() {} "
                    f"{returned} OnMonitor() {{ return {{}}; }} }};",
                )
                with self.assertRaisesMessage(
                    ValueError,
                    f"User/xrobot.yaml: m: OnMonitor of M returns {returned}; it must return void",
                ):
                    self.generate({"modules": [{"module": "M", "id": "m"}]})

    def test_a_known_void_result_needs_no_assertion(self):
        for declaration in (
            "void OnMonitor() {}",
            "virtual void OnMonitor() {}",
            "[[maybe_unused]] static inline void OnMonitor() {}",
            "void OnMonitor() const noexcept {}",
        ):
            with self.subTest(declaration=declaration):
                self.module("M", f"class M {{ public: M() {{}} {declaration} }};")
                code = self.generate({"modules": [{"module": "M", "id": "m"}]})
                self.assertIn("m.OnMonitor();", code)
                self.assertNotIn("static_assert", code)

    def test_a_result_the_index_cannot_read_keeps_one_compact_assertion(self):
        # 返回类型是别名、auto、尾置返回类型，或各重载写法不一，或来自 using 声明：
        # 生成时无法判断，由编译器检查。
        # An alias, auto, a trailing return type, overloads that disagree, or a using
        # declaration: generation cannot tell, and the compiler checks.
        for body in (
            "using Result = void;\n  Result OnMonitor() {}",
            "auto OnMonitor() {}",
            "auto OnMonitor() -> void {}",
            "void OnMonitor() {}\n  int OnMonitor(int) { return 0; }",
        ):
            with self.subTest(body=body):
                self.module("M", f"class M {{ public: M() {{}}\n  {body}\n}};")
                code = self.generate({"modules": [{"module": "M", "id": "m"}]})
                self.assertEqual(code.count("static_assert"), 1)
                self.assertIn(
                    "  static_assert(std::is_void_v<decltype(m.OnMonitor())>,\n"
                    '                "m.OnMonitor() must return void");\n',
                    code,
                )
                self.assertIn("#include <type_traits>\n", code)

    def test_the_result_of_an_inherited_monitor_is_read_from_its_base(self):
        self.module(
            "M",
            "struct Core { int OnMonitor() { return 1; } };\nclass M : public Core { public: M() {} };",
        )
        with self.assertRaisesMessage(
            ValueError, "User/xrobot.yaml: m: OnMonitor of M returns int; it must return void"
        ):
            self.generate({"modules": [{"module": "M", "id": "m"}]})
        self.module(
            "M", "struct Core { void OnMonitor() {} };\nclass M : public Core { public: M() {} };"
        )
        self.assertNotIn("static_assert", self.generate({"modules": [{"module": "M", "id": "m"}]}))


class Templates(BspTestCase):
    """类模板模块的模板实参。
    Template arguments of class-template Modules.
    """

    def setUp(self):
        super().setUp()
        self.entry(MAIN)
        self.module(
            "Buf",
            "template <typename T, unsigned N = 4>\nclass Buf { public: explicit Buf(T init = T{}) {} };",
        )
        self.module("Def", "template <typename T = int>\nclass Def { public: Def() {} };")

    def test_template_arguments_and_defaults(self):
        code = self.generate(
            {
                "modules": [
                    {
                        "module": "Buf",
                        "id": "a",
                        "template_args": ["float"],
                        "args": [{"init": "1.0F"}],
                    },
                    {
                        "module": "Buf",
                        "id": "b",
                        "template_args": ["int", "8"],
                        "args": [{"init": "2"}],
                    },
                    {"module": "Def", "id": "c"},
                ]
            }
        )
        self.assertIn("static Buf<float> a(1.0F);", code)
        self.assertIn("static Buf<int, 8> b(2);", code)
        self.assertIn("static Def<> c;", code)
        self.assertNotIn("Implicit", code)

    def test_instance_id_equal_to_a_class_template_name_is_rejected(self):
        with self.assertRaisesMessage(
            ValueError,
            "User/xrobot.yaml: Buf: instance id Buf is also a class name in the loaded "
            "Modules; use a lower-case id such as buf",
        ):
            self.generate({"modules": [{"module": "Def", "id": "Buf"}]})

    def test_missing_and_extra_template_arguments_are_errors(self):
        with self.assertRaisesMessage(
            ValueError, "User/xrobot.yaml: a: Template argument Buf.T must be specified"
        ):
            self.generate({"modules": [{"module": "Buf", "id": "a"}]})
        with self.assertRaisesMessage(
            ValueError, "User/xrobot.yaml: a: Too many template arguments for Def"
        ):
            self.generate(
                {"modules": [{"module": "Def", "id": "a", "template_args": ["int", "int"]}]}
            )


class Overloads(BspTestCase):
    """按参数名选择重载的构造函数。
    Selecting an overloaded constructor by parameter names.
    """

    def setUp(self):
        super().setUp()
        self.entry(MAIN)

    def test_parameter_names_select_the_constructor(self):
        self.module("Foo", "class Foo { public: Foo(int count = 0) {} Foo(float gain = 0.0f) {} };")
        code = self.generate({"modules": [{"module": "Foo", "id": "f", "args": [{"gain": "1"}]}]})
        self.assertIn("  static Foo f(xrobot_generated::Implicit<float>(1));\n", code)
        # 转换函数只在需要它的头文件里定义。
        # The conversion function is defined only in a header that needs it.
        self.assertIn(
            "namespace xrobot_generated\n{\n"
            "// Converts implicitly, so the compiler still warns about constants that change value.\n"
            "template <typename P>\n"
            "constexpr P Implicit(std::type_identity_t<P> value)\n{\n  return value;\n}\n"
            "}  // namespace xrobot_generated\n",
            code,
        )
        self.assertIn("#include <type_traits>\n", code)

    def test_same_names_are_told_apart_only_by_explicit_types(self):
        self.module(
            "Foo", "class Foo { public: Foo(int value = 0) {} Foo(float value = 0.0f) {} };"
        )
        self.assertIn(
            "Implicit<float>(1.0f)",
            self.generate({"modules": [{"module": "Foo", "id": "f", "args": [{"value": "1.0f"}]}]}),
        )
        self.assertIn(
            "Implicit<int>(static_cast<int>(Read()))",
            self.generate(
                {
                    "modules": [
                        {
                            "module": "Foo",
                            "id": "f",
                            "args": [{"value": "static_cast<int>(Read())"}],
                        }
                    ]
                }
            ),
        )
        with self.assertRaisesMessage(
            ValueError,
            "User/xrobot.yaml: f: Foo: constructor is ambiguous for the supplied names and "
            "explicit types",
        ):
            self.generate(
                {"modules": [{"module": "Foo", "id": "f", "args": [{"value": "Read()"}]}]}
            )

    def test_a_dependency_after_a_defaulted_parameter_is_not_a_supported_constructor(self):
        self.module("Foo", "class Foo { public: Foo(int count = 10, Port& port) {} };")
        with self.assertRaisesMessage(
            ValueError,
            "User/xrobot.yaml: f: Foo: no compliant constructor; line 4: port: dependency "
            "without a default appears after value configuration",
        ):
            self.generate({"modules": [{"module": "Foo", "id": "f"}]})


class CompileCheckProbe(BspTestCase):
    """模块 CI 使用的构造探针。
    The constructor probe the Module CI compiles.
    """

    def test_probe_uses_null_placeholders_and_is_never_a_program(self):
        self.module(
            "Foo",
            """#include <cstdlib>
struct Uart { Uart() = delete; };
template <typename T>
class Foo { public:
  struct Param { int period = 10; T scale{}; };
  static Param Make() { return {}; }
  Foo(Uart& uart, Uart* optional, Param p = {}, Param q = Make()) { std::abort(); }
  void OnMonitor() { std::abort(); }
};""",
        )
        out = self.tmp / "probe" / "check.cpp"
        code = generate_compile_check("team/Foo", load_modules(self.project), out, ["float"])
        self.assertEqual(out.read_text(encoding="utf-8"), code)
        # 没有 main、循环和 #line：探针只编译，从不链接运行。
        # No main, loop or #line: the probe is compiled, never linked or run.
        self.assertEqual(
            code,
            """// Generated by `xrobot check-module` for Module CI; do not edit by hand.

#include <type_traits>

#include "Foo.hpp"
#include "libxr.hpp"
#include "thread.hpp"

namespace xrobot_generated
{
void XRobotCompileCheck()
{
  // Compilation only: this function must never be invoked.
  [[maybe_unused]] static void* xr_ci_null = static_cast<void*>(nullptr);

  // module_0: team/Foo<float>
  static const Foo<float>::Param xr_module_0_p = {
      .period = 10,
      .scale = {},
  };
  static Foo<float> module_0(*static_cast<std::remove_reference_t<Uart&>*>(xr_ci_null),
                             *static_cast<std::remove_reference_t<Uart*>*>(xr_ci_null),
                             xr_module_0_p, Foo<float>::Make());
  module_0.OnMonitor();
}
}  // namespace xrobot_generated
""",
        )

    def test_library_probe_includes_the_header_and_errors_leave_the_output_alone(self):
        self.module(
            "Lib",
            "class Lib { public: Lib() {} };",
            manifest="/* === MODULE MANIFEST V2 ===\nstandalone: false\n=== END MANIFEST === */\n",
        )
        self.module(
            "Foo", "class Foo { static int Secret(); public: Foo(int count = Secret()) {} };"
        )
        library = self.tmp / "library.cpp"
        self.assertEqual(
            generate_compile_check("team/Lib", load_modules(self.project), library),
            '#include "Lib.hpp"\n',
        )
        self.assertEqual(library.read_text(encoding="utf-8"), '#include "Lib.hpp"\n')
        out = self.write(self.tmp / "check.cpp", "original")
        with self.assertRaisesMessage(ValueError, "Expression uses non-public member Foo::Secret"):
            generate_compile_check("team/Foo", load_modules(self.project), out)
        self.assertEqual(out.read_text(encoding="utf-8"), "original")


@requires_cxx
class GeneratedCpp(CxxMixin, BspTestCase):
    """生成的头文件能够编译、绑定、构造并调用 OnMonitor。
    The generated header compiles, binds, constructs and calls OnMonitor.
    """

    def setUp(self):
        super().setUp()
        self.entry(MAIN)

    def test_seeded_defaults_that_use_namespace_names_compile(self):
        self.module(
            "Qux",
            "namespace qux { enum Mode { A, B }; inline constexpr int kN = 3;\n"
            "  struct Param { Mode mode = A; int n = kN; }; }\n"
            "class Qux { public:\n  explicit Qux(qux::Param param = {}) { (void)param; } };",
        )
        config = self.config("modules: []\n")
        modules = load_modules(self.project)
        config_edit.add_instance(
            config, "Qux", modules, TypeIndex.for_modules(modules), "qux", "User/xrobot.yaml"
        )
        self.assertIn(".mode = qux::A", generate(self.project, config))
        self.compile(execute=False)

    def test_static_config_lifetime_nested_values_and_pointer_binding(self):
        self.module(
            "Foo",
            """#include <cassert>
#include <initializer_list>
struct Left { long padding[3]{}; };
struct Right { int value = 17; };
struct Device : Left, Right {};
class Foo { public:
  struct Param { struct Gain { float kp, ki; }; Gain gain; int number; };
  Foo(Right& right, Right* optional, const Param& p = Param{}, std::initializer_list<int> values = {7, 8})
      : p_(p), values_(values) { assert(&right == optional); assert(right.value == 17); }
  void OnMonitor() const noexcept {
    assert(p_.gain.kp == 1 && p_.gain.ki == 2); assert(p_.number == 3); assert(*values_.begin() == 7);
  }
 private:
  const Param& p_; std::initializer_list<int> values_;
};""",
        )
        self.entry(
            '#include "Foo.hpp"\n#include "xrobot_main.hpp"\n'
            "int main() { static Device device; XR_REGISTER(device, Device); XROBOT_MAIN(); }\n"
        )
        code = self.generate(
            {
                "modules": [
                    {
                        "module": "Foo",
                        "id": "f",
                        "args": [
                            {"right": "device"},
                            {"optional": "device"},
                            {"p": {"gain": {"kp": "1.0f", "ki": "2.0f"}, "number": "3"}},
                            {"values": ["7", "8"]},
                        ],
                    }
                ]
            }
        )
        self.assertIn("static const Foo::Param xr_f_p = {", code)
        self.assertIn("static const std::initializer_list<int> xr_f_values = {7, 8};", code)
        self.compile()

    def test_base_adjustment_and_cv_pointer_storage(self):
        self.stub(
            "thread.hpp",
            """#pragma once
#include <cstdlib>
#include <cassert>
inline int constructors = 0, monitors = 0;
inline int alternate = 9;
inline int** expected_storage = nullptr;
inline const void* expected_right = nullptr;
namespace LibXR { struct Thread { static void Sleep(unsigned n) {
  assert(n == 1000); assert(constructors == 1); assert(*expected_storage == &alternate);
  if (monitors == 3) std::_Exit(0);
} }; }
""",
        )
        self.module(
            "Probe",
            """#include "thread.hpp"
#include <cstdint>
struct Left { std::uintptr_t padding[4]{}; };
struct Right { int value = 17; };
struct Device : Left, Right {};
class Probe {
 public:
  Probe(Right& right, int*& pointer, const int& configuration, volatile int& flags, const int* const& fixed) {
    assert(static_cast<const void*>(&right) == expected_right);
    assert(&pointer == expected_storage); assert(configuration == 4);
    assert(*fixed == 4); assert(flags == 5); flags = 6;
    pointer = &alternate; ++constructors;
  }
  ~Probe() { std::abort(); }
  void OnMonitor() { ++monitors; }
};""",
        )
        self.entry("""#include "Probe.hpp"
#include "xrobot_main.hpp"
int main() {
  Device device; int value = 3; int* pointer = &value;
  const int configuration = 4; volatile int flags = 5;
  const int* const fixed = &configuration;
  expected_storage = &pointer;
  expected_right = static_cast<Right*>(&device);
  assert(expected_right != static_cast<void*>(&device));
  XR_REGISTER(device, Device);
  XR_REGISTER(pointer, int*);
  XR_REGISTER(configuration, const int);
  XR_REGISTER(flags, volatile int);
  XR_REGISTER(fixed, const int* const);
  XROBOT_MAIN();
}
""")
        self.generate(
            {
                "modules": [
                    {
                        "module": "Probe",
                        "id": "probe0",
                        "args": [
                            {"right": "device"},
                            {"pointer": "pointer"},
                            {"configuration": "configuration"},
                            {"flags": "flags"},
                            {"fixed": "fixed"},
                        ],
                    }
                ]
            }
        )
        # MinGW 没有 UBSan 运行库。
        # MinGW has no UBSan runtime.
        sanitizer = (
            []
            if "clang" in Path(CXX).name or os.name == "nt"
            else ["-fsanitize=undefined", "-fno-sanitize-recover=all"]
        )
        self.compile(extra=sanitizer)

    def test_named_overload_is_not_reselected_by_literal_type(self):
        self.module(
            "Foo",
            """#include <cassert>
class Foo { public:
  Foo(int count = 0) { (void)count; assert(false && "wrong constructor"); }
  Foo(float gain = 0.0f) { assert(gain == 1.0f); }
};""",
        )
        self.generate({"modules": [{"module": "Foo", "id": "f", "args": [{"gain": "1"}]}]})
        self.compile()

    def test_factory_prvalue_keeps_guaranteed_copy_elision(self):
        self.module(
            "Foo",
            """struct Config {
  Config() = default;
  Config(const Config&) = delete;
  Config(Config&&) = delete;
};
class Foo { public:
  static Config DefaultConfig() { return Config{}; }
  Foo(Config config = DefaultConfig()) { (void)config; }
  Foo(int count = 0) { (void)count; }
};""",
        )
        self.generate(
            {
                "modules": [
                    {"module": "Foo", "id": "f", "args": [{"config": "Foo::DefaultConfig()"}]}
                ]
            }
        )
        self.compile()

    def test_explicit_only_conversion_is_rejected_by_the_compiler(self):
        self.module(
            "Foo",
            """struct Config { explicit Config(int) {} };
class Foo { public:
  Foo(Config config = Config{0}) { (void)config; }
};""",
        )
        self.generate({"modules": [{"module": "Foo", "id": "f", "args": [{"config": "1"}]}]})
        self.assertRegex(self.compile(expected=False), r"xrobot\.yaml:2:\d+: error")

    def test_downcast_of_an_unlocatable_type_is_rejected_by_the_compiler(self):
        self.stub(
            "libxr.hpp", "#pragma once\nnamespace LibXR { struct CAN {}; struct FDCAN : CAN {}; }\n"
        )
        self.entry(
            '#include "xrobot_main.hpp"\n'
            "int main() { static LibXR::FDCAN fdcan1; LibXR::CAN& can1 = fdcan1;\n"
            "  XR_REGISTER(can1, LibXR::CAN); XROBOT_MAIN(); }\n"
        )
        # 只有一个构造函数时 C++ 自己拒绝；有几个时，Implicit<T> 保持同样的规则。
        # With one constructor C++ rejects it; with several, Implicit<T> keeps the same rule.
        for constructors in (
            "explicit Motor(LibXR::FDCAN& can) { (void)can; }",
            "explicit Motor(LibXR::FDCAN& can) { (void)can; }\n  explicit Motor(int id) { (void)id; }",
        ):
            with self.subTest(constructors=constructors):
                self.module(
                    "Motor", f'#include "libxr.hpp"\nclass Motor {{ public:\n  {constructors}\n}};'
                )
                self.generate(
                    {"modules": [{"module": "Motor", "id": "motor", "args": [{"can": "can1"}]}]}
                )
                self.assertRegex(self.compile(expected=False), r"xrobot\.yaml:2:\d+: error")

    def test_a_reference_alias_registration_binds_the_base(self):
        self.stub(
            "libxr.hpp",
            "#pragma once\nnamespace LibXR { struct CAN { int id = 5; }; struct FDCAN : CAN {}; }\n",
        )
        self.module(
            "Motor",
            '#include <cassert>\n#include "libxr.hpp"\n'
            "class Motor { public: explicit Motor(LibXR::CAN& can) { assert(can.id == 5); } };",
        )
        self.entry(
            '#include "xrobot_main.hpp"\n'
            "int main() { static LibXR::FDCAN fdcan1; LibXR::CAN& can1 = fdcan1;\n"
            "  XR_REGISTER(can1, LibXR::CAN); XROBOT_MAIN(); }\n"
        )
        self.generate({"modules": [{"module": "Motor", "id": "motor", "args": [{"can": "can1"}]}]})
        self.compile()

    def test_constant_narrowing_keeps_the_compiler_warning(self):
        self.module(
            "Foo",
            "#include <cstdint>\nclass Foo { public: explicit Foo(std::uint8_t id = 1) { (void)id; } };",
        )
        self.generate({"modules": [{"module": "Foo", "id": "f", "args": [{"id": "300"}]}]})
        self.assertIn("44", self.compile(expected=False))
        # 有几个构造函数时经 Implicit<T>，同样保留这个警告。
        # With several constructors the value goes through Implicit<T>, which keeps it.
        self.module(
            "Foo",
            "#include <cstdint>\nclass Foo { public:\n"
            "  explicit Foo(std::uint8_t id = 1) { (void)id; }\n"
            "  explicit Foo(float gain = 1.0f) { (void)gain; } };",
        )
        self.generate({"modules": [{"module": "Foo", "id": "f", "args": [{"id": "300"}]}]})
        self.assertIn("44", self.compile(expected=False))

    def test_monitor_order_and_accepted_signatures(self):
        self.stub(
            "thread.hpp",
            """#pragma once
#include <cstdlib>
#include <cassert>
inline int stage = 0, extra = 0;
namespace LibXR { struct Thread { static void Sleep(unsigned) { assert(stage == 4); assert(extra == 2); std::_Exit(0); } }; }
""",
        )
        self.module(
            "A",
            '#include "thread.hpp"\nclass A { public: A() { assert(stage++ == 0); } '
            "void OnMonitor() { assert(stage++ == 2); } };",
        )
        self.module(
            "B",
            '#include "thread.hpp"\n#include "A.hpp"\nclass B { public: explicit B(A& a) '
            "{ (void)a; assert(stage++ == 1); } void OnMonitor() const noexcept { assert(stage++ == 3); } };",
        )
        variants = [
            ("NoMonitor", ""),
            ("Private", "private: void OnMonitor() { std::abort(); }"),
            ("Defaulted", "void OnMonitor(int = 0) { ++extra; }"),
            ("Overloaded", "void OnMonitor() { ++extra; } void OnMonitor(int) { std::abort(); }"),
        ]
        for name, monitor in variants:
            self.module(
                name, f'#include "thread.hpp"\nclass {name} {{ public: {name}() {{}} {monitor} }};'
            )
        entries = [{"module": "A", "id": "a"}, {"module": "B", "id": "b", "args": [{"a": "a"}]}]
        entries += [{"module": name, "id": name.lower() + "0"} for name, _ in variants]
        code = self.generate({"modules": entries})
        self.assertNotIn("nomonitor0.OnMonitor", code)
        self.assertNotIn("private0.OnMonitor", code)
        self.compile()

    def test_a_monitor_result_the_index_cannot_read_fails_to_compile_when_it_is_not_void(self):
        self.module("Wrong", "class Wrong { public: Wrong() {} auto OnMonitor() { return 1; } };")
        self.generate({"modules": [{"module": "Wrong", "id": "wrong"}]})
        self.assertIn("wrong.OnMonitor() must return void", self.compile(expected=False))

    def test_inherited_monitor_is_called(self):
        self.stub(
            "thread.hpp",
            "#pragma once\n#include <cstdlib>\ninline int calls = 0;\n"
            "namespace LibXR { struct Thread { static void Sleep(unsigned) "
            "{ std::_Exit(calls == 1 ? 0 : 3); } }; }\n",
        )
        self.module(
            "Derived",
            '#include "thread.hpp"\nstruct DerivedCore { void OnMonitor() { ++calls; } };\n'
            "class Derived : public DerivedCore { public: Derived() {} };",
        )
        self.assertIn(
            "derived.OnMonitor();",
            self.generate({"modules": [{"module": "Derived", "id": "derived"}]}),
        )
        self.compile()

    def test_local_caller_defined_registered_types(self):
        self.module(
            "Probe",
            "#include <cassert>\ntemplate <class T> class Probe { public: explicit Probe(T& value) "
            "{ assert(value.number == 7); } };",
        )
        entry = {
            "module": "Probe",
            "id": "p",
            "template_args": ["std::remove_reference_t<decltype(dev)>"],
            "args": [{"value": "dev"}],
        }
        mains = {
            "local struct": "int main() { struct Local { int number = 7; }; static Local dev; "
            "XR_REGISTER(dev, Local); XROBOT_MAIN(); }",
            "anonymous typedef": "int main() { typedef struct { int number; } Local; static Local dev{7}; "
            "XR_REGISTER(dev, Local); XROBOT_MAIN(); }",
            "declared after the header": "struct View { int number = 7; };\n"
            "int main() { static View dev; XR_REGISTER(dev, View); XROBOT_MAIN(); }",
            "local alias of a base": "struct Port { int number = 7; }; struct Device : Port { int number = 1; };\n"
            "int main() { using LocalView = Port; static Device dev; "
            "XR_REGISTER(dev, LocalView); XROBOT_MAIN(); }",
        }
        for label, body in mains.items():
            with self.subTest(label):
                self.entry('#include "xrobot_main.hpp"\n' + body + "\n")
                self.generate({"modules": [entry]})
                self.compile()

    def test_caller_array_bounds_and_non_type_template_arguments(self):
        self.module(
            "Probe",
            "#include <cassert>\ntemplate <class T> class Probe { public: explicit Probe(T& value) "
            "{ assert(value.size() == 2); } };",
        )
        entry = {
            "module": "Probe",
            "id": "p",
            "template_args": ["std::remove_reference_t<decltype(values)>"],
            "args": [{"value": "values"}],
        }
        mains = [
            "int main() { enum { Count = 2 }; static std::array<int, Count> values{}; "
            "XR_REGISTER(values, std::array<int, Count>); XROBOT_MAIN(); }",
            "int main() { constexpr unsigned Count{2}; static std::array<int, Count> values{}; "
            "XR_REGISTER(values, std::array<int, Count>); XROBOT_MAIN(); }",
            "template <unsigned Count> void Launch() { static std::array<int, Count> values{}; "
            "XR_REGISTER(values, std::array<int, Count>); XROBOT_MAIN(); }\nint main() { Launch<2>(); }",
        ]
        for body in mains:
            with self.subTest(body=body):
                self.entry('#include <array>\n#include "xrobot_main.hpp"\n' + body + "\n")
                self.generate({"modules": [entry]})
                self.compile()

    def test_generated_template_parameters_do_not_shadow_user_names(self):
        self.module(
            "Probe",
            "template <class T> class Probe { public: explicit Probe(T& value) { value.number = 7; } };",
        )
        self.entry(
            '#include "xrobot_main.hpp"\nint main() { struct Local { int number = 1; }; static Local XrViewType0; '
            "XR_REGISTER(XrViewType0, Local); XROBOT_MAIN(); }\n"
        )
        self.generate(
            {
                "modules": [
                    {
                        "module": "Probe",
                        "id": "XrViewType1",
                        "template_args": ["std::remove_reference_t<decltype(XrViewType0)>"],
                        "args": [{"value": "XrViewType0"}],
                    }
                ]
            }
        )
        self.compile()

    def test_array_and_function_pointer_registrations(self):
        self.module(
            "Probe",
            """#include <cassert>
using Array = int[2];
using Callback = int (*)(int);
class Probe { public:
  Probe(Array& values, Callback& fn) { assert(values[0] == 3 && values[1] == 5); assert(fn(4) == 8); values[1] = 9; }
};""",
        )
        self.entry(
            '#include "xrobot_main.hpp"\nint Twice(int x) { return x * 2; }\n'
            "int main() { static Array values = {3, 5}; static Callback fn = Twice;\n"
            "  XR_REGISTER(values, Array); XR_REGISTER(fn, Callback); XROBOT_MAIN(); }\n"
        )
        code = self.generate(
            {
                "modules": [
                    {"module": "Probe", "id": "p", "args": [{"values": "values"}, {"fn": "fn"}]}
                ]
            }
        )
        self.assertIn("XRobotMain(Array& values, Callback& fn)\n{", code)
        self.compile()

    def test_caller_function_pointer_typedef(self):
        self.module(
            "Probe",
            "#include <cassert>\ntemplate <class T> class Probe { public: explicit Probe(T& fn) "
            "{ assert(fn(3) == 6); } };",
        )
        self.entry(
            '#include "xrobot_main.hpp"\nint Twice(int x) { return x * 2; }\n'
            "int main() { typedef int (*LocalCallback)(int); static LocalCallback fn = Twice; "
            "XR_REGISTER(fn, LocalCallback); XROBOT_MAIN(); }\n"
        )
        self.generate(
            {
                "modules": [
                    {
                        "module": "Probe",
                        "id": "p",
                        "template_args": ["std::remove_reference_t<decltype(fn)>"],
                        "args": [{"fn": "fn"}],
                    }
                ]
            }
        )
        self.compile()

    def test_pointer_covariance_through_a_reference_is_rejected(self):
        self.module(
            "Probe",
            "struct Base {}; struct Derived : Base {};\n"
            "class Probe { public: explicit Probe(Base*& pointer) { (void)pointer; } };",
        )
        self.entry(
            '#include "Probe.hpp"\n#include "xrobot_main.hpp"\n'
            "int main() { static Derived d; static Derived* ptr = &d; XR_REGISTER(ptr, Derived*); XROBOT_MAIN(); }\n"
        )
        self.generate({"modules": [{"module": "Probe", "id": "p", "args": [{"pointer": "ptr"}]}]})
        self.compile(expected=False)

    def test_const_object_cannot_bind_a_mutable_reference(self):
        self.module("Probe", "class Probe { public: explicit Probe(int& value) { (void)value; } };")
        for registration in ("int", "const int"):
            with self.subTest(registration=registration):
                self.entry(
                    '#include "xrobot_main.hpp"\nint main() { static const int value = 1; '
                    f"XR_REGISTER(value, {registration}); XROBOT_MAIN(); }}\n"
                )
                self.generate(
                    {"modules": [{"module": "Probe", "id": "p", "args": [{"value": "value"}]}]}
                )
                self.compile(expected=False)

    def test_one_object_binds_distinct_and_virtual_bases(self):
        self.module(
            "Probe",
            """#include <cassert>
struct Port { virtual ~Port() = default; virtual int Read() { return 1; } };
struct Left : virtual Port {};
struct Right { int value = 7; };
struct Device : Left, Right { int Read() override { return 11; } };
class Probe { public: Probe(Port& p, Right& r) { assert(p.Read() == 11); assert(r.value == 7); } };""",
        )
        self.entry(
            '#include "Probe.hpp"\n#include "xrobot_main.hpp"\n'
            "int main() { static Device dev; XR_REGISTER(dev, Device); XROBOT_MAIN(); }\n"
        )
        self.generate(
            {"modules": [{"module": "Probe", "id": "p", "args": [{"p": "dev"}, {"r": "dev"}]}]}
        )
        self.compile()

    def test_an_ambiguous_base_is_rejected_by_the_compiler(self):
        self.module(
            "Probe",
            "struct Port {}; struct A : Port {}; struct B : Port {}; struct Twice : A, B {};\n"
            "class Probe { public: explicit Probe(Port& p) { (void)p; } };",
        )
        self.entry(
            '#include "Probe.hpp"\n#include "xrobot_main.hpp"\n'
            "int main() { static Twice dev; XR_REGISTER(dev, Twice); XROBOT_MAIN(); }\n"
        )
        self.generate({"modules": [{"module": "Probe", "id": "p", "args": [{"p": "dev"}]}]})
        self.compile(expected=False)

    def test_a_later_instance_used_inside_an_expression_fails_in_cpp(self):
        self.module("A", "class A { public: A(int n = 1) { (void)n; } int Get() { return 1; } };")
        self.generate(
            {
                "modules": [
                    {"module": "A", "id": "a", "args": [{"n": "b.Get()"}]},
                    {"module": "A", "id": "b", "args": [{"n": "1"}]},
                ]
            }
        )
        self.compile(expected=False)

    def test_no_instances_and_no_registrations_compile_pedantically(self):
        self.generate({"modules": []})
        self.compile(extra=["-pedantic-errors"])

    def test_a_registration_must_name_an_object_visible_at_the_call(self):
        self.module("A", "class A { public: explicit A(int& value) { (void)value; } };")
        self.entry(
            '#include "xrobot_main.hpp"\nint main() { XR_REGISTER(v, int); XROBOT_MAIN(); int v = 1; (void)v; }\n'
        )
        self.generate({"modules": [{"module": "A", "id": "a", "args": [{"value": "v"}]}]})
        self.compile(expected=False)

    def test_entry_function_can_be_called_directly(self):
        self.module(
            "Probe",
            "struct Port {}; class Probe { public: explicit Probe(Port& port) { (void)port; } "
            "void OnMonitor() {} };",
        )
        self.entry(
            '#include "Probe.hpp"\n#include "xrobot_main.hpp"\n'
            "static Port port;\nvoid Run() { XR_REGISTER(port, Port); XROBOT_MAIN(); }\n"
            "int main() { ::XRobotMain(port); }\n"
        )
        self.generate(
            {"modules": [{"module": "Probe", "id": "probe_0", "args": [{"port": "port"}]}]}
        )
        self.compile()

    def test_constructor_errors_are_diagnosed_without_a_call(self):
        self.module("Probe", "class Probe { public: explicit Probe(int value) { (void)value; } };")
        self.entry(
            '#include "xrobot_main.hpp"\nint main() { return 0; }\n// XROBOT_MAIN();\n'
            "void Run() { XROBOT_MAIN(); }\n"
        )
        self.generate({"modules": [{"module": "Probe", "id": "p", "args": [{"value": '"wrong"'}]}]})
        self.compile(expected=False)

    def test_header_is_self_contained_and_idempotent(self):
        self.module(
            "Probe", "class Probe { public: explicit Probe(int value = 3) { (void)value; } };"
        )
        self.generate({"modules": [{"module": "Probe", "id": "p", "args": [{"value": "3"}]}]})
        self.entry(
            '#include "xrobot_main.hpp"\n#include "xrobot_main.hpp"\nint main() { return 0; }\n'
            "void Run() { XROBOT_MAIN(); }\n"
        )
        self.compile()

    def test_the_compile_check_probe_compiles_but_is_never_linked(self):
        self.module(
            "Foo",
            """#include <cstdlib>
struct Uart { Uart() = delete; };
struct FooParam { int period = 10; float scale = 1.0f; };
class Foo { public:
  Foo(Uart& uart, Uart* optional, FooParam param = {}, int period = 10) {
    (void)uart; (void)optional; (void)param; (void)period; std::abort(); }
  void OnMonitor() { std::abort(); }
};""",
        )
        out = self.tmp / "check.cpp"
        generate_compile_check("team/Foo", load_modules(self.project), out)
        self.compile(out, execute=False)


@requires_cxx
class LineDirectivesInCpp(CxxMixin, BspTestCase):
    """编译器报错指回配置中的行。
    Compiler errors point back at configuration lines.
    """

    def setUp(self):
        super().setUp()
        self.entry(MAIN)

    def test_a_value_of_the_wrong_type_is_reported_at_its_yaml_line(self):
        self.module(
            "Probe",
            'class Probe { public: explicit Probe(int value = 1, const char* name = "p") '
            "{ (void)value; (void)name; } };",
        )
        config = self.config(
            "modules:\n  - module: Probe\n    id: p\n    args:\n"
            "      - value: 1\n      - name: 42\n"
        )
        generate(self.project, config)
        output = self.compile(expected=False)
        self.assertRegex(output, r"xrobot\.yaml:2:\d*:? ?\s*(error|note)", output)
        self.assertRegex(
            output,
            r"invalid conversion|cannot convert|no known conversion|no viable|cannot initialize",
        )

    def test_an_arithmetic_value_error_is_reported_at_its_yaml_line(self):
        self.module(
            "Probe",
            "class Probe { public: explicit Probe(int first = 1, int value = 1) "
            "{ (void)first; (void)value; } };",
        )
        config = self.config(
            "# product\n\nmodules:\n  - module: Probe\n    id: p\n    args:\n"
            '      - first: 2\n      - value: "\\"wrong\\""\n'
        )
        generate(self.project, config)
        output = self.compile(expected=False)
        self.assertRegex(output, r"xrobot\.yaml:4:\d+: error", output)

    def test_errors_after_an_instance_are_reported_in_the_header(self):
        self.module("Wrong", "class Wrong { public: Wrong() {} auto OnMonitor() { return 1; } };")
        config = self.config("modules:\n  - module: Wrong\n    id: wrong\n")
        code = generate(self.project, config)
        line = next(
            i for i, text in enumerate(code.split("\n"), 1) if text.startswith("  static_assert(")
        )
        output = self.compile(expected=False)
        self.assertRegex(output, rf"xrobot_main\.hpp:{line}:\d+: error", output)


class Registrations(TempDirTestCase):
    """从入口源文件读取 XR_REGISTER。
    Reading XR_REGISTER from the entry source.
    """

    def setUp(self):
        super().setUp()
        self.root = self.tmp

    def read_entry(self, text):
        """读取入口源文件文本中的 XR_REGISTER。
        Read the XR_REGISTER calls of an entry source text.
        """
        return read_registrations(self.write("app_main.cpp", text))

    def test_name_type_and_line_are_read(self):
        records = self.read_entry(
            '#include "xrobot_main.hpp"\nvoid f() {\n  XR_REGISTER(led, LibXR::GPIO);\n'
            "  XR_REGISTER(values, std::array<int, 2>);\n}\n"
        )
        self.assertEqual(
            [(r["name"], r["type"], r["line"]) for r in records],
            [("led", "LibXR::GPIO", 3), ("values", "std::array<int, 2>", 4)],
        )

    def test_comments_and_string_literals_are_not_registrations(self):
        records = self.read_entry(
            "// XR_REGISTER(fake, Wrong);\n/* XR_REGISTER(a, B); */\n"
            'const char* s = "XR_REGISTER(x, y)";\nXR_REGISTER(real, int);\n'
        )
        self.assertEqual([r["name"] for r in records], ["real"])

    def test_each_invalid_registration_is_rejected_with_its_line(self):
        one_type = (
            "XR_REGISTER registers one type per name: XR_REGISTER(name, Type). To expose the "
            "object as another type, declare a reference (e.g. `LibXR::CAN& can1 = fdcan1;`) "
            "and register that name separately"
        )
        conditional = (
            "XR_REGISTER inside #if/#ifdef/#ifndef is not supported; the generator cannot "
            "evaluate build options"
        )
        cases = [
            ("XR_REGISTER(dev, Left, Right);\n", f"app_main.cpp:1: {one_type}"),
            ("XR_REGISTER(dev);\n", f"app_main.cpp:1: {one_type}"),
            (
                "#define REGISTER_ALL XR_REGISTER(x, int)\nint x;\n",
                "app_main.cpp:1: XR_REGISTER inside a preprocessor directive is not supported",
            ),
            ("XR_REGISTER(x, int\n", "app_main.cpp: malformed XR_REGISTER invocation"),
            (
                "XR_REGISTER(x, int);\nXR_REGISTER(x, long);\n",
                "app_main.cpp:2: duplicate XR_REGISTER name x",
            ),
            (
                "XR_REGISTER(class, int);\n",
                "app_main.cpp:1: registration name class is a C++ keyword",
            ),
            (
                "XR_REGISTER(xr_led, int);\n",
                "app_main.cpp:1: registration name xr_led uses a prefix reserved for generated names",
            ),
            (
                "XR_REGISTER(ASSERT, int);\n",
                "app_main.cpp:1: registration name ASSERT is a macro name",
            ),
        ]
        for directive in ("#if defined(OPTION)", "#ifdef OPTION", "#ifndef OPTION"):
            cases.append(
                (
                    f"int x;\n{directive}\nXR_REGISTER(x, int);\n#endif\n",
                    f"app_main.cpp:3: {conditional}",
                )
            )
        for cpp_type in ("int&", "LibXR::CAN &", "int&&"):
            cases.append(
                (
                    f"XR_REGISTER(x, {cpp_type});\n",
                    "app_main.cpp:1: register object types, not reference types: x",
                )
            )
        for text, message in cases:
            with self.subTest(text=text):
                with self.assertRaises(ConfigError) as context:
                    self.read_entry(text)
                self.assertEqual(str(context.exception), message)

    def test_registration_after_a_closed_conditional_is_accepted(self):
        records = self.read_entry(
            "#if OPTION\nint y;\n#else\nint z;\n#endif\nint x;\nXR_REGISTER(x, int);\n"
        )
        self.assertEqual([r["name"] for r in records], ["x"])

    def test_every_registration_error_is_reported(self):
        with self.assertRaises(ConfigError) as context:
            self.read_entry(
                "XR_REGISTER(a, int&);\nXR_REGISTER(b, X, Y);\nXR_REGISTER(class, int);\n"
            )
        self.assertEqual(
            [line.split(": ", 1)[0] for line in str(context.exception).splitlines()],
            ["app_main.cpp:1", "app_main.cpp:2", "app_main.cpp:3"],
        )

    def test_types_declared_by_the_caller_are_marked(self):
        records = self.read_entry(
            "struct Global {};\nvoid f() {\n  struct Local {};\n  Local d; Global g; int n;\n"
            "  XR_REGISTER(d, Local);\n  XR_REGISTER(g, Global);\n  XR_REGISTER(n, int);\n"
            "  XR_REGISTER(p, LibXR::GPIO);\n}\n"
        )
        self.assertEqual(
            {r["name"]: r["caller_view"] for r in records},
            {"d": True, "g": True, "n": False, "p": False},
        )


class CallerDefinedNames(TestCase):
    """入口源文件在登记点之前声明的名字（保守地收集，多收集无害）。
    The names the entry source declares before a registration, collected conservatively
    (extra names do no harm).
    """

    SOURCE = (
        "namespace board { struct Motor {}; }\n"
        "enum class Mode { Fast, Slow };\n"
        "enum Color { Red, Green = 2 };\n"
        "typedef struct { int x; } Pair;\n"
        "typedef void (*Handler)(int);\n"
        "void f() { constexpr int Count{2}; struct Local {}; using namespace board; }\n"
        "using Alias = board::Motor;\n"
        "using board::Speed;\n"
        "template <typename T, int Size = 4> struct Buffer {};\n"
    )

    def test_every_declaration_kind_is_collected(self):
        tokens = code_tokens(self.SOURCE)
        names = caller_defined_names(tokens, len(tokens))
        # * 表示块内的 using namespace：任何名字都可能来自调用处。
        # * stands for a block-scope using namespace: any name may come from the caller.
        for name in (
            "Motor",
            "Mode",
            "Fast",
            "Slow",
            "Color",
            "Red",
            "Green",
            "Pair",
            "Handler",
            "Count",
            "Local",
            "*",
            "Alias",
            "Speed",
            "Buffer",
            "T",
            "Size",
        ):
            with self.subTest(name=name):
                self.assertIn(name, names)

    def test_declarations_after_the_stop_are_not_collected(self):
        tokens = code_tokens(self.SOURCE)
        stop = next(i for i, t in enumerate(tokens) if t.text == "void")
        names = caller_defined_names(tokens, stop)
        self.assertIn("Pair", names)
        self.assertEqual(
            names & {"Count", "Local", "*", "Alias", "Speed", "Buffer", "T", "Size"}, set()
        )
