"""把 Modules/modules.yaml 的请求解析为确定的 commit，写入 xrobot.lock 并检出模块。
Resolve the requests of Modules/modules.yaml to exact commits, write xrobot.lock and check
out the Modules; the build itself belongs to native CMake.

modules.yaml 列出请求的模块（并用 ``xrobot:`` 固定工具版本）；xrobot.lock 记录依赖闭包中每个
模块的确切 commit，写出后即为依据：
modules.yaml lists the requested Modules (and pins the tool with ``xrobot:``); xrobot.lock
records the exact commit of every Module in the dependency closure and is authoritative
once written:

- 不带 ``--update`` 时已锁定的模块不移动；新增、删除或修改的请求只影响对应条目。
  Without ``--update`` locked Modules do not move; added, removed or changed requests
  affect only their entries.
- ``--update <module>...`` 只重新解析指定模块；不带名字时重新解析全部。
  ``--update <module>...`` re-resolves the named Modules; without names, all of them.
- ``--frozen`` 严格按 lock 检出，请求变化即报错，从不写 lock。
  ``--frozen`` checks out exactly the lock, fails on changed requests, never writes it.
- ``--offline`` 不联网，只用已有的检出。
  ``--offline`` uses the existing checkouts without network.
- ``--release-ref`` 拒绝尚未进入目标发布线的 commit。
  ``--release-ref`` refuses commits that are not on the target release line.
"""

import os
import re
import sys
from collections.abc import Callable
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from urllib.parse import urlparse
from urllib.request import url2pathname

import yaml
from xr_syntax.i18n import tr

from xrobot.git import checkout_state, git, head_commit, origin_url
from xrobot.module_parser import manifest_from_text
from xrobot.project import Project, atomic_write
from xrobot.source_manager import SourceManager, SourceUnavailable, load_yaml, validate_id

MODULES_KEYS = ("modules", "xrobot")
TOOL_REPOSITORIES = {
    "xrobot": "https://github.com/xrobot-org/XRobot.git",
    "generator": "https://github.com/xrobot-org/LibXR_CppCodeGenerator.git",
}

LOCK_NOTICE = "# Generated by `xrobot setup`; do not edit by hand.\n"
# 不在 Git 仓库中的 BSP 没有分支可供 same/same-or-dev 跟随。
# A BSP outside Git has no branch for same/same-or-dev to follow.
NO_BRANCH = "no-branch"


def _offline_hint() -> str:
    """不联网时可用 --offline 的提示。
    The hint that --offline works without network.
    """
    return tr(
        "`xrobot setup --offline` works without network when xrobot.lock matches "
        "Modules/modules.yaml and the Modules are checked out",
        "xrobot.lock 与 Modules/modules.yaml 一致且模块都已检出时，`xrobot setup --offline` "
        "不需要联网",
    )


def _fetch(folder: Path, *args: str) -> None:
    """运行 git fetch；失败时附上 --offline 的提示。
    Run git fetch; a failure adds the --offline hint.
    """
    try:
        git(folder, "fetch", *args)
    except ValueError as error:
        raise ValueError(f"{error}\n{_offline_hint()}") from error


def _has_commit(folder: Path, commit: str | None) -> bool:
    """folder 中的检出是否已含有 commit；检出正在这个 commit 上时不调用 git。
    Whether the checkout in folder already holds commit; git is not run when the checkout
    is at that commit.
    """
    if not commit:
        return False
    if head_commit(folder) == commit:
        return True
    return git(folder, "cat-file", "-t", commit, check=False) == "commit"


def _follows_the_bsp(req: dict, parent_context: tuple | list | None) -> bool:
    """请求是否为要跟随一个不在 Git 中的 BSP 分支的 same/same-or-dev。
    Whether the request is a same/same-or-dev one that would follow the branch of a BSP
    outside Git.
    """
    return (
        req["ref"] in ("same", "same-or-dev")
        and not req.get("context_ref")
        and parent_context is not None
        and parent_context[0] == NO_BRANCH
    )


def local_locator(value: str) -> str | None:
    """本地仓库的路径；网络地址返回 None。
    The filesystem path of a local repository; None for a network Git URL.

    Raises:
        ValueError: 指向其他主机的 file:// 地址。
            A file:// URL with another host.
    """
    if value.startswith("file://"):
        parsed = urlparse(value)
        if parsed.netloc not in ("", "localhost"):
            raise ValueError(
                tr(
                    "Use a network Git URL for a non-local file host",
                    "file:// 地址指向其他主机时，请改用网络 Git 地址",
                )
            )
        return url2pathname(parsed.path)
    if re.match(r"^[A-Za-z][A-Za-z0-9+.-]*://", value) or value.startswith("git@"):
        return None
    return value


def portable_locator(value: str, lock_directory: Path) -> str:
    """写入 lock 的仓库地址：本地仓库写成相对 lock 的路径，网络地址不变。
    The repository as written to the lock: a local one relative to the lock, a network URL
    unchanged.

    Raises:
        ValueError: 本地仓库无法用相对 lock 的路径表示（如在另一个盘符）。
            The local repository cannot be expressed relative to the lock (another drive).
    """
    local = local_locator(value)
    if local is None:
        return value
    path = Path(local)
    if not path.is_absolute():
        path = Path(lock_directory) / path  # 已经相对于 lock / already relative to the lock
    try:
        return Path(os.path.relpath(path.resolve(), lock_directory)).as_posix()
    except ValueError as error:
        raise ValueError(
            tr(
                "Local source cannot be expressed relative to this lock; use a portable "
                "repository URL",
                "本地源无法写成相对这个 lock 的路径；请使用可移植的仓库地址",
            )
        ) from error


def expanded_locator(value: str, lock_directory: Path) -> str:
    """lock 中仓库地址的可用形式：相对路径展开为绝对路径。
    A usable form of a repository from the lock: relative paths made absolute.
    """
    local = local_locator(value)
    return value if local is None else str((lock_directory / local).resolve())


def repository_identity(value: str) -> str:
    """用于比较的仓库标识：忽略协议、主机大小写、.git 和斜杠。
    A repository identity for comparison: scheme, host case, .git and slashes ignored.
    """
    local = local_locator(value)
    if local is not None:
        return "file:" + str(Path(local).resolve()).casefold()
    text = value.strip()
    match = re.match(r"^git@([^:]+):(.+)$", text)
    if match:
        host, path = match.groups()
    else:
        parsed = urlparse(text)
        host, path = parsed.hostname or "", parsed.path
    path = path.strip("/")
    if path.endswith(".git"):
        path = path[:-4]
    host = host.casefold()
    if host == "github.com":
        path = path.casefold()
    return host + "/" + path


def same_repository(left: str, right: str) -> bool:
    """两个地址是否指向同一个仓库。
    Whether two addresses name the same repository.
    """
    return repository_identity(left) == repository_identity(right)


def request(value: str | dict, canonical: bool = False) -> dict:
    """解析一条请求：``owner/Repo@ref`` 或 ``{id, ref, context_ref}``。
    Parse one request: ``owner/Repo@ref`` or ``{id, ref, context_ref}``.

    Args:
        value: modules.yaml 或模块 manifest 中的一项。
            One item of modules.yaml or of a Module manifest.
        canonical: 为真时 id 必须是 owner/Repo。
            When true the id must be owner/Repo.

    Returns:
        含 id、ref（未写为 None），以及可选 context_ref 的映射。
        A mapping with id, ref (None when not written) and an optional context_ref.

    Raises:
        ValueError: 写法不对。
            The request is malformed.
    """
    if isinstance(value, str):
        identity, separator, ref = value.partition("@")
        result = {"id": identity, "ref": ref if separator else None}
    elif isinstance(value, dict) and set(value) <= {"id", "ref", "context_ref"}:
        result = {"id": value.get("id"), "ref": value.get("ref")}
        if value.get("context_ref"):
            result["context_ref"] = str(value["context_ref"])
    else:
        raise ValueError(
            tr(
                "Dependency must be owner/repo@ref or {id, ref, context_ref}",
                "依赖必须写成 owner/repo@ref 或 {id, ref, context_ref}",
            )
        )
    if not isinstance(result["id"], str) or not result["id"]:
        raise ValueError(tr("Dependency is missing its package id", "依赖缺少包 id"))
    if canonical:
        validate_id(result["id"])
    if result["ref"] is not None:
        result["ref"] = str(result["ref"])
        if not result["ref"] or result["ref"].startswith("-"):
            raise ValueError(tr("Invalid dependency ref", "无效的依赖 ref"))
    return result


def context(value: str) -> tuple[str, str]:
    """把 refs/heads/<name> 或 refs/tags/<name> 转成 ("branch"|"tag", name)。
    Turn refs/heads/<name> or refs/tags/<name> into ("branch"|"tag", name).

    Raises:
        ValueError: 不是完整的 refs/heads/ 或 refs/tags/ 引用。
            Not a full refs/heads/ or refs/tags/ reference.
    """
    if value.startswith("refs/heads/"):
        return ("branch", value[len("refs/heads/") :])
    if value.startswith("refs/tags/"):
        return ("tag", value[len("refs/tags/") :])
    raise ValueError(
        tr(
            "A context/release ref must start with refs/heads/ or refs/tags/",
            "context/release ref 必须以 refs/heads/ 或 refs/tags/ 开头",
        )
    )


def read_modules_yaml(path: str | Path) -> tuple[list[dict], str | None]:
    """读取 modules.yaml：请求列表和固定的 XRobot 版本。
    Read modules.yaml: the request list and the pinned XRobot version.

    Returns:
        (请求列表, 固定版本或 None)。
        (requests, the pin or None).

    Raises:
        ValueError: 有未知的键、modules 不是列表，或固定版本格式不对。
            An unknown key, modules is not a list, or the pin is malformed.
    """
    data = load_yaml(path) if Path(path).exists() else {}
    unknown = [key for key in data if key not in MODULES_KEYS]
    if unknown:
        raise ValueError(
            tr(
                f"{path}: unknown key(s) {', '.join(unknown)}; allowed: {', '.join(MODULES_KEYS)}",
                f"{path}: 未知的键 {'、'.join(unknown)}；允许的键：{'、'.join(MODULES_KEYS)}",
            )
        )
    if not isinstance(data.get("modules", []), list):
        raise ValueError(
            tr(
                f"{path}: modules must be a list of package requests",
                f"{path}: modules 必须是包请求的列表",
            )
        )
    pin = data.get("xrobot")
    if pin is not None and not _valid_pin(str(pin)):
        raise ValueError(
            tr(
                f"{path}: xrobot must be a release version (e.g. 1.0.0) or a 40-hex commit",
                f"{path}: xrobot 必须是发布版本号（例如 1.0.0）或 40 位提交号",
            )
        )
    return [request(value, canonical=True) for value in data.get("modules") or []], (
        str(pin) if pin is not None else None
    )


def _valid_pin(value: str) -> bool:
    """固定版本是否为发布版本号或 40 位 commit。
    Whether a pin is a release version or a 40-hex commit.
    """
    return bool(
        re.fullmatch(r"\d+\.\d+\.\d+(?:[.\-+][0-9A-Za-z.\-]+)?", value)
        or re.fullmatch(r"[0-9a-f]{40}", value)
    )


class Resolver:
    """把请求解析成 commit 并检出到 Modules/<owner>/<Repo>。
    Resolves requests to commits and checks them out into Modules/<owner>/<Repo>.

    Attributes:
        pinned: 保持 lock 中 commit 的条目（未要求更新且请求未变）。
            Entries that keep their locked commit (not updated, request unchanged).
        locked: lock 中的全部条目；BSP 不在 Git 中时，跟随分支的请求保持它们。
            Every lock entry; in a BSP outside Git, branch-following requests keep these.
        resolved: 已解析的条目，最后写入 lock。
            The resolved entries, written to the lock at the end.
        warnings: 需要告诉用户的情况。
            Things to tell the user.
    """

    def __init__(
        self,
        modules_dir: Path,
        source_manager: SourceManager | Callable[[], SourceManager] | None = None,
        offline: bool = False,
        pinned: dict | None = None,
        locked: dict | None = None,
        without_git: bool = False,
    ) -> None:
        """准备解析；modules_dir 是 Modules 目录，其余参数即同名属性。
        Prepare a resolution; modules_dir is the Modules folder and the other arguments are the
        attributes of the same names.
        """
        self.directory = Path(modules_dir).resolve()
        # 一个 SourceManager，或首次使用时才调用的加载函数。
        # A SourceManager, or a function that loads it on first use.
        self._sources = source_manager
        self.offline = offline
        self.pinned = pinned or {}
        self.locked = locked or {}
        self.without_git = without_git
        self.warnings: list[str] = []
        self.prepared: dict[str, dict] = {}
        self.resolved: dict[str, dict] = {}
        self.stack: list[str] = []

    @property
    def sources(self) -> SourceManager | None:
        """源；以加载函数给出时在首次使用时加载。
        The Sources; loaded on first use when given as a loader.
        """
        if callable(self._sources):
            self._sources = self._sources()
        return self._sources

    def fetch_url(self, identity: str, repo: str) -> str:
        """拉取代码的地址：有镜像源时为镜像，否则为 repo。
        Where to fetch from: the mirror when a mirror Source lists the package, else repo.
        """
        mirror = self.sources.mirror_url(identity) if self.sources is not None else None
        return mirror or repo

    def prepare(self, identity: str, repo: str, commit: str | None = None) -> Path:
        """确保 Modules/<identity> 是 repo 的检出，返回该目录。
        Make sure Modules/<identity> is a checkout of repo and return its folder.

        离线时没有源可用来识别镜像地址；已含有 lock 记录的 commit 的检出，不论 origin 都接受。
        Offline there are no Sources to recognize a mirror origin; a checkout that already
        holds the locked commit is accepted whatever its origin.

        Args:
            commit: lock 中的 commit；检出里已有它时不 fetch。
                The locked commit; a checkout that holds it is not fetched.

        Raises:
            ValueError: 目录不是 Git 检出、origin 不对、离线时缺少检出，或 git 失败。
                The folder is not a Git checkout, origin is wrong, a checkout is missing
                offline, or git failed.
        """
        validate_id(identity)
        folder = self.directory / identity
        if self.directory not in folder.resolve().parents:
            raise ValueError(
                tr(
                    "Source path leaves the project module directory: " + identity,
                    "源路径超出了项目的模块目录：" + identity,
                )
            )
        if identity in self.prepared:
            if not same_repository(self.prepared[identity]["repo"], repo):
                raise ValueError(
                    tr(
                        "Conflicting source repositories for " + identity,
                        identity + " 的源仓库相互冲突",
                    )
                )
            return folder
        # 只有需要克隆，或 origin 不是原仓库（可能是镜像）时才读取源。
        # The Sources are read only to clone, or when origin is not the original
        # repository (it may be a mirror).
        if folder.exists():
            if not (folder / ".git").exists():
                raise ValueError(
                    tr(
                        f"Refusing to overwrite non-Git directory: {folder}",
                        f"拒绝覆盖不是 Git 仓库的目录：{folder}",
                    )
                )
            actual = origin_url(folder)
            if not same_repository(actual, repo):
                if self.offline:
                    known = _has_commit(folder, commit)
                else:
                    known = same_repository(actual, self.fetch_url(identity, repo))
                if not known:
                    raise ValueError(
                        tr(
                            f"Source mismatch for {identity}: {actual} != {repo}",
                            f"{identity} 的源不一致：{actual} != {repo}",
                        )
                    )
        elif self.offline:
            raise ValueError(tr("Offline source missing: " + identity, "离线时缺少源：" + identity))
        else:
            folder.parent.mkdir(parents=True, exist_ok=True)
            git(None, "clone", "--", self.fetch_url(identity, repo), str(folder))
        # 检出里已有锁定的 commit 时不必联网。
        # A checkout that already holds the locked commit needs no network.
        if not self.offline and not _has_commit(folder, commit):
            _fetch(folder, "--prune", "--tags", "origin")
        self.prepared[identity] = {"repo": repo, "folder": folder}
        return folder

    def resolve_ref(
        self, folder: Path, ref: str | None, parent_context: tuple | list | None = None
    ) -> tuple[str, str, str]:
        """在 folder 的仓库中把 ref 解析成 commit。
        Resolve ref to a commit in the repository of folder.

        Args:
            ref: 分支、标签、commit、refs/heads/…、refs/tags/…、same、same-or-dev；
                None 为仓库的默认分支。
                A branch, tag, commit, refs/heads/..., refs/tags/..., same or
                same-or-dev; None is the default branch of the repository.
            parent_context: same/same-or-dev 跟随的 ("branch"|"tag", 名字)。
                The ("branch"|"tag", name) that same/same-or-dev follows.

        Returns:
            (commit, "branch"|"tag"|"commit", 名字)。
            (commit, "branch"|"tag"|"commit", name).

        Raises:
            ValueError: 无法解析；信息说明原因，由调用者补上请求者和模块。
                ref cannot be resolved; the message gives the reason, and the caller adds
                the requester and the Module.
        """
        if ref in ("same", "same-or-dev"):
            if not parent_context or parent_context[0] not in ("branch", "tag"):
                raise ValueError(
                    tr(
                        "there is no branch or tag to follow: the BSP checkout is not on a "
                        "branch, or the requesting Module is pinned to a commit; pass "
                        "--context-ref refs/heads/<branch>",
                        "没有可跟随的分支或 tag：BSP 的检出不在分支上，或发出请求的模块固定在某个"
                        "提交；请传入 --context-ref refs/heads/<分支>",
                    )
                )
            kind, name = parent_context
            full = ("refs/remotes/origin/" if kind == "branch" else "refs/tags/") + name
            sha = git(folder, "rev-parse", "--verify", full + "^{commit}", check=False)
            if sha:
                return sha, kind, name
            if kind == "tag" or ref == "same":
                raise ValueError(
                    tr(
                        f"the repository has no {kind} {name}",
                        f"仓库中没有{'分支' if kind == 'branch' else ' tag'} {name}",
                    )
                )
            if name == "dev":
                raise ValueError(
                    tr(
                        "the repository has no dev branch; request an explicit tag, commit or "
                        "branch",
                        "仓库中没有 dev 分支；请明确请求一个 tag、提交或分支",
                    )
                )
            ref = "refs/heads/dev"
            if not git(
                folder, "rev-parse", "--verify", "refs/remotes/origin/dev^{commit}", check=False
            ):
                raise ValueError(
                    tr(
                        f"the repository has neither a {name} branch nor a dev branch; request "
                        "an explicit tag, commit or branch",
                        f"仓库中既没有 {name} 分支，也没有 dev 分支；请明确请求一个 tag、提交"
                        "或分支",
                    )
                )
        if ref is None:
            symbolic = git(
                folder, "symbolic-ref", "--quiet", "refs/remotes/origin/HEAD", check=False
            )
            if not symbolic:
                raise ValueError(
                    tr(
                        "the repository has no default branch; request an explicit ref",
                        "仓库没有默认分支；请明确请求一个 ref",
                    )
                )
            ref = "refs/heads/" + symbolic[len("refs/remotes/origin/") :]
        if ref.startswith("refs/heads/"):
            name = ref[len("refs/heads/") :]
            lookup, kind = "refs/remotes/origin/" + name, "branch"
        elif ref.startswith("refs/tags/"):
            name = ref[len("refs/tags/") :]
            lookup, kind = ref, "tag"
        else:
            branch = git(
                folder,
                "rev-parse",
                "--verify",
                "refs/remotes/origin/" + ref + "^{commit}",
                check=False,
            )
            tag = git(
                folder, "rev-parse", "--verify", "refs/tags/" + ref + "^{commit}", check=False
            )
            if branch and tag:
                raise ValueError(
                    tr(
                        f"{ref} is both a branch and a tag; write refs/heads/{ref} or "
                        f"refs/tags/{ref}",
                        f"{ref} 既是分支也是 tag；请写 refs/heads/{ref} 或 refs/tags/{ref}",
                    )
                )
            if branch or tag:
                return branch or tag, "branch" if branch else "tag", ref
            if not re.fullmatch(r"[0-9a-fA-F]{7,40}", ref):
                raise ValueError(
                    tr(
                        f"the repository has no branch, tag or commit {ref}",
                        f"仓库中没有名为 {ref} 的分支、tag 或提交",
                    )
                )
            lookup, kind, name = ref, "commit", ref
        sha = git(folder, "rev-parse", "--verify", lookup + "^{commit}", check=False)
        if not sha:
            raise ValueError(tr(f"the repository has no {ref}", f"仓库中没有 {ref}"))
        return sha, kind, name

    def _requester(self) -> str:
        """请求当前模块的一方：modules.yaml 或模块链。
        Who asks for the Module being resolved: modules.yaml or a chain of Modules.
        """
        return " -> ".join(self.stack) or "Modules/modules.yaml"

    def _resolve(
        self, identity: str, folder: Path, req: dict, parent_context: tuple | list | None
    ) -> tuple[str, str, str]:
        """resolve_ref，报错时带上请求者和被请求的模块。
        resolve_ref, with the requester and the requested Module in its errors.
        """
        try:
            return self.resolve_ref(folder, req["ref"], parent_context)
        except ValueError as error:
            target = identity if req["ref"] is None else f"{identity}@{req['ref']}"
            raise ValueError(
                tr(
                    f"{self._requester()} requests {target}: {error}",
                    f"{self._requester()} 请求 {target}：{error}",
                )
            ) from None

    def _keep_without_branch(self, identity: str, req: dict) -> dict:
        """BSP 不在 Git 中时，跟随分支的请求保留的 lock 条目。
        The locked entry a branch-following request keeps in a BSP outside Git.

        Raises:
            ValueError: lock 中没有这个模块，无法选择 commit。
                The Module is not in the lock, so no commit can be picked.
        """
        kept = self.locked.get(identity)
        target = f"{identity}@{req['ref']}"
        if kept is None:
            raise ValueError(
                tr(
                    f"{self._requester()} requests {target}, which needs the BSP branch to "
                    "pick a commit, but the BSP is not a Git repository; request an explicit "
                    f"ref such as {identity}@dev, or put the BSP in a Git repository",
                    f"{self._requester()} 请求 {target}，需要根据 BSP 所在的分支选择提交，"
                    f"但 BSP 不是 Git 仓库；请明确请求一个 ref（例如 {identity}@dev），"
                    "或把 BSP 放进 Git 仓库",
                )
            )
        self.warnings.append(
            tr(
                f"the BSP is not a Git repository, so {target} keeps {kept['commit'][:12]} "
                "from xrobot.lock",
                f"BSP 不是 Git 仓库，因此 {target} 沿用 xrobot.lock 中的 {kept['commit'][:12]}",
            )
        )
        return kept

    def visit(self, req: dict, parent_context: tuple | list | None = None) -> None:
        """解析一条请求及其依赖闭包，记入 resolved。
        Resolve one request and its dependency closure into resolved.

        Raises:
            ValueError: 请求的是 BSP、依赖成环、同一模块解析到不同 commit，或解析失败。
                The request names a BSP, dependencies form a cycle, one Module resolves to
                two commits, or resolution fails.
        """
        identity = self.sources.resolve_id(req["id"])
        package = self.sources.packages[identity]
        if package["type"] != "module":
            raise ValueError(
                tr(
                    f"{identity} is a BSP in the Sources, not a Module dependency",
                    f"{identity} 在源中是 BSP，不能作为模块依赖",
                )
            )
        if identity in self.stack:
            cycle = " -> ".join(self.stack + [identity])
            raise ValueError(tr("Package dependency cycle: " + cycle, "包依赖成环：" + cycle))
        pinned = self.pinned.get(identity)
        if pinned is None and self.without_git and _follows_the_bsp(req, parent_context):
            pinned = self._keep_without_branch(identity, req)
        if pinned is not None:
            folder = self.prepare(identity, expanded_locator(pinned["repo"], self.directory.parent))
            explicit = req["ref"] not in (None, "same", "same-or-dev")
            if explicit:
                sha, _, _ = self._resolve(identity, folder, req, parent_context)
                if sha != pinned["commit"]:
                    raise ValueError(
                        tr(
                            f"{self._requester()} requires {identity} at {req['ref']}, but "
                            f"xrobot.lock keeps {pinned['commit'][:12]}; run "
                            f"`xrobot setup --update {identity}`",
                            f"{self._requester()} 要求 {identity} 位于 {req['ref']}，"
                            f"但 xrobot.lock 保持在 {pinned['commit'][:12]}；请运行 "
                            f"`xrobot setup --update {identity}`",
                        )
                    )
            if identity in self.resolved:
                return
            self.resolved[identity] = dict(
                pinned, context=list(parent_context or ("commit", pinned["commit"]))
            )
            sha, logical = pinned["commit"], self.resolved[identity]["context"]
        else:
            folder = self.prepare(identity, package.get("canonical", package["repo"]))
            sha, kind, name = self._resolve(identity, folder, req, parent_context)
            logical = list(context(req["context_ref"])) if req.get("context_ref") else [kind, name]
            if identity in self.resolved:
                previous = self.resolved[identity]
                if previous["commit"] != sha:
                    raise ValueError(
                        tr(
                            f"Dependency conflict for {identity}: {previous['commit'][:12]} vs "
                            f"{sha[:12]} ({' -> '.join(self.stack)})",
                            f"{identity} 的依赖冲突：{previous['commit'][:12]} 与 {sha[:12]}"
                            f"（{' -> '.join(self.stack)}）",
                        )
                    )
                return
            self.resolved[identity] = {
                "repo": package.get("canonical", package["repo"]),
                "source": package["source"],
                "requested": req["ref"],
                "resolved_ref": name,
                "ref_kind": kind,
                "context": logical,
                "commit": sha,
            }
        self.stack.append(identity)
        try:
            header = identity.rsplit("/", 1)[-1] + ".hpp"
            text = git(folder, "show", sha + ":" + header, check=False)
            if text is None:
                raise ValueError(
                    tr(
                        f"{identity}@{sha[:12]} has no primary {header}",
                        f"{identity}@{sha[:12]} 中没有主头文件 {header}",
                    )
                )
            for dep in manifest_from_text(text, str(folder / header)).depends:
                self.visit(request(dep, canonical=True), tuple(logical))
        finally:
            self.stack.pop()

    def materialize(self) -> None:
        """把每个模块检出到解析出的 commit；不丢弃本地修改，出错时回滚已切换的模块。
        Check out every resolved commit; local work is never discarded, and Modules already
        switched are moved back on an error.

        已在锁定 commit 的检出不动，其中未提交的修改（开发模块时的常态）保持原样。
        A checkout already at its commit is left alone, and its uncommitted changes (the
        normal state while developing a Module) stay as they are.

        Raises:
            ValueError: 要移动的模块有未提交的修改或未推送的提交、两个模块定义同名的类，或
                检出失败。
                A Module that has to move has uncommitted changes or unpushed commits, two
                Modules define the same class, or a checkout fails.
        """
        before = {}
        for identity, entry in self.resolved.items():
            folder = self.prepared[identity]["folder"]
            if head_commit(folder) == entry["commit"]:
                continue
            head, branch, dirty = checkout_state(folder)
            if dirty:
                raise ValueError(
                    tr(
                        f"{identity} has uncommitted changes; they are kept, but the lock cannot "
                        "move it. Commit and push them, or discard them, first",
                        f"{identity} 有未提交的修改；修改会保留，但 lock 无法移动它。"
                        "请先提交并推送这些修改，或者丢弃它们",
                    )
                )
            unpublished = head and not _published(folder, head)
            if unpublished and not self.offline:
                # 没有 fetch 过时，远端分支可能还不包含已推送的提交。
                # Without a fetch the remote branches may not yet show a pushed commit.
                _fetch(folder, "--prune", "--tags", "origin")
                unpublished = not _published(folder, head)
            if unpublished:
                raise ValueError(
                    tr(
                        f"{identity} is at local commit {head[:12]} that is not on any remote "
                        "branch or tag. While developing a module, keep your changes "
                        "uncommitted; when they are ready, push them to a branch of the module "
                        f"and run `xrobot setup --update {identity}`",
                        f"{identity} 位于本地提交 {head[:12]}，它不在任何远端分支或 tag 上。"
                        "开发模块期间请保持修改未提交；准备好后推送到模块的某个分支，"
                        f"再运行 `xrobot setup --update {identity}`",
                    )
                )
            gitdir = Path(git(folder, "rev-parse", "--absolute-git-dir"))
            before[identity] = (head, branch, (gitdir / "index").exists())
        by_name = {}
        for identity in self.resolved:
            name = identity.rsplit("/", 1)[-1]
            if name in by_name and by_name[name] != identity:
                raise ValueError(
                    tr(
                        f"{by_name[name]} and {identity} both define the global class {name}; "
                        "use only one of them",
                        f"{by_name[name]} 和 {identity} 都定义了全局类 {name}；只能使用其中一个",
                    )
                )
            by_name[name] = identity
        applied = []
        try:
            for identity in before:
                entry = self.resolved[identity]
                folder = self.prepared[identity]["folder"]
                applied.append(identity)
                if not _has_commit(folder, entry["commit"]):
                    if self.offline:
                        raise ValueError(
                            tr(
                                "Offline commit missing for " + identity,
                                "离线时缺少 " + identity + " 的提交",
                            )
                        )
                    _fetch(folder, "origin", entry["commit"])
                git(folder, "checkout", "--detach", entry["commit"])
                if (folder / ".gitmodules").exists():
                    args = ["submodule", "update", "--init", "--recursive"]
                    if self.offline:
                        args.append("--no-fetch")
                    git(folder, *args)
        except Exception:
            for identity in reversed(applied):
                head, branch, has_index = before[identity]
                if has_index and head:
                    git(self.prepared[identity]["folder"], "checkout", branch or head, check=False)
            raise


def _published(folder: Path, commit: str) -> bool:
    """commit 是否已在某个远端分支或标签上。
    Whether commit is on a remote branch or a tag.
    """
    remote = git(folder, "branch", "-r", "--contains", commit, check=False)
    if remote:
        return True
    return bool(git(folder, "tag", "--contains", commit, check=False))


def validate_locked_graph(resolver: Resolver, roots: list[dict]) -> None:
    """按锁定 commit 的头文件重走依赖，确认 lock 与依赖闭包一致；不解析移动的 ref。
    Walk the dependencies from the headers of the locked commits and check that the lock
    is exactly the dependency closure; moving refs are not resolved.

    Raises:
        ValueError: lock 缺条目、多条目、ref 与请求不符，或依赖成环。
            The lock misses or has extra entries, a ref does not match its request, or the
            dependencies form a cycle.
    """
    records = resolver.resolved
    visited, active = set(), []

    def primary_header(identity: str) -> str | None:
        """锁定 commit 上模块主头文件的内容；没有时为 None。
        The Module's primary header at its locked commit; None when it is missing.
        """
        folder = resolver.prepared[identity]["folder"]
        header = identity.rsplit("/", 1)[-1] + ".hpp"
        return git(folder, "show", records[identity]["commit"] + ":" + header, check=False)

    # 每次 git show 都要启动一个进程（Windows 上约 20 ms）；先并行读出全部主头文件。
    # Every git show starts a process (about 20 ms on Windows); read all primary headers
    # in parallel first.
    known = [identity for identity in records if identity in resolver.prepared]
    with ThreadPoolExecutor(max_workers=8) as pool:
        texts = dict(zip(known, pool.map(primary_header, known), strict=True))

    def visit(req: dict) -> None:
        """检查一条请求在 lock 中有唯一且相符的条目，再依次检查它的依赖；发现依赖环时报错。
        Check that a request has exactly one matching lock entry, then check its dependencies; a
        dependency cycle is an error.
        """
        candidates = [key for key in records if key.casefold() == req["id"].casefold()]
        if len(candidates) != 1:
            raise ValueError(
                tr(
                    f"xrobot.lock is missing or ambiguous for {req['id']}; run `xrobot setup`",
                    f"xrobot.lock 中 {req['id']} 缺失或有歧义；请运行 `xrobot setup`",
                )
            )
        identity = candidates[0]
        row = records[identity]
        kind, name = row.get("ref_kind"), row.get("resolved_ref")
        selector = req.get("ref")
        if selector and selector not in ("same", "same-or-dev"):
            if selector.startswith("refs/heads/") or selector.startswith("refs/tags/"):
                if [kind, name] != list(context(selector)):
                    raise ValueError(
                        tr(
                            "Locked ref does not match requested ref for " + identity,
                            identity + " 锁定的 ref 与请求的 ref 不一致",
                        )
                    )
            elif re.fullmatch(r"[0-9a-fA-F]{7,40}", selector) and kind == "commit":
                if not row["commit"].startswith(selector.lower()):
                    raise ValueError(
                        tr(
                            "Locked commit does not match requested SHA for " + identity,
                            identity + " 锁定的提交与请求的 SHA 不一致",
                        )
                    )
            elif name != selector:
                raise ValueError(
                    tr(
                        "Locked ref does not match manifest for " + identity,
                        identity + " 锁定的 ref 与 manifest 不一致",
                    )
                )
        if identity in active:
            cycle = " -> ".join(active + [identity])
            raise ValueError(
                tr("Dependency cycle in project lock: " + cycle, "项目 lock 中的依赖成环：" + cycle)
            )
        if identity in visited:
            return
        active.append(identity)
        text = texts[identity] if identity in texts else primary_header(identity)
        if text is None:
            raise ValueError(
                tr(
                    "Primary header missing from locked commit for " + identity,
                    identity + " 锁定的提交中缺少主头文件",
                )
            )
        header = identity.rsplit("/", 1)[-1] + ".hpp"
        for dep in manifest_from_text(text, header).depends:
            visit(request(dep, canonical=True))
        active.pop()
        visited.add(identity)

    for root in roots:
        visit(root)
    if visited != set(records):
        extra = sorted(set(records) - visited)
        raise ValueError(
            tr(
                "xrobot.lock contains Modules outside the declared dependency closure: "
                f"{', '.join(extra)}; run `xrobot setup`",
                f"xrobot.lock 中有声明的依赖之外的模块：{'、'.join(extra)}；请运行 `xrobot setup`",
            )
        )


def release_line(release_ref: str) -> str | None:
    """BSP 目标 ref 要求的发布线（G3）：dev，或 master/main/标签对应的 master。
    The release line a BSP target ref requires (G3): dev, or master for master, main and
    tags.

    Returns:
        "dev"、"master"，或功能分支时的 None。
        "dev", "master", or None for a feature branch.
    """
    kind, name = context(release_ref)
    if kind == "branch" and name == "dev":
        return "dev"
    if (kind == "branch" and name in ("master", "main")) or kind == "tag":
        return "master"
    return None


def _line_ref(folder: Path, line: str) -> str | None:
    """发布线在 folder 中的远端引用：origin/dev、origin/master，或仅有 main 时的 origin/main。
    The remote ref of a release line in folder: origin/dev, origin/master, or origin/main
    for a main-only repository.
    """
    names = [line] if line == "dev" else ["master", "main"]
    for name in names:
        ref = "refs/remotes/origin/" + name
        if git(folder, "rev-parse", "--verify", ref + "^{commit}", check=False):
            return ref
    return None


def check_released(resolver: Resolver, release_ref: str, offline: bool = False) -> None:
    """发布门禁：每个锁定的 commit 都必须在 BSP 目标对应的模块发布线上（G3）。
    Release gate: every locked commit must be on the Module release line of the BSP target
    (G3).

    Raises:
        ValueError: 列出不在发布线上的模块，或拉取失败。
            Lists the Modules whose commits are not on the line, or a fetch failed.
    """
    line = release_line(release_ref)
    if line is None:
        return
    problems = []
    for identity, row in sorted(resolver.resolved.items()):
        folder = resolver.prepared[identity]["folder"]
        requested = row.get("requested")
        if row.get("ref_kind") == "tag" and requested not in (None, "same", "same-or-dev"):
            # 显式请求的 tag 本身就是发布。
            # An explicitly requested tag is released by definition.
            continue
        if not offline:
            _fetch(folder, "origin", "+refs/heads/*:refs/remotes/origin/*")
        target = _line_ref(folder, line)
        if target is None:
            if row.get("ref_kind") == "commit":
                # 没有发布线的第三方模块只能显式锁定 commit。
                # A third-party Module without the line has explicit commit pins only.
                continue
            problems.append(
                tr(
                    f"{identity} has no {line} branch; request an explicit tag or commit",
                    f"{identity} 没有 {line} 分支；请明确请求一个 tag 或提交",
                )
            )
            continue
        contained = (
            git(folder, "merge-base", "--is-ancestor", row["commit"], target, check=False)
            is not None
        )
        if not contained:
            branch = target.split("/")[-1]
            follow = "dev" if line == "dev" else "master"
            problems.append(
                tr(
                    f"{identity}: locked commit {row['commit'][:12]} is not on {branch} "
                    "(feature branch not merged, or merged by squash/rebase); after merging the "
                    f"Module, run `xrobot setup --update {identity} --context-ref "
                    f"refs/heads/{follow}`",
                    f"{identity}: 锁定的提交 {row['commit'][:12]} 不在 {branch} 上（功能分支还没有"
                    "合并，或以 squash/rebase 方式合并）；合并模块后请运行 "
                    f"`xrobot setup --update {identity} --context-ref refs/heads/{follow}`",
                )
            )
    if problems:
        raise ValueError("\n".join(problems))


def check_tool_pins(
    project: Project, release_ref: str, offline: bool = False, cache: str | Path | None = None
) -> None:
    """工具的固定版本遵守与模块相同的发布线规则（G3）。
    Tool pins follow the same release-line rule as Modules (G3).

    Raises:
        ValueError: 工具未固定版本，或固定的 commit 不在发布线上。
            A tool is not pinned, or its pinned commit is not on the line.
    """
    line = release_line(release_ref)
    if line is None:
        return
    pins = {}
    _, pins["xrobot"] = read_modules_yaml(project.modules_yaml)
    if project.libxr_config.is_file():
        data = yaml.safe_load(project.libxr_config.read_text(encoding="utf-8")) or {}
        if isinstance(data, dict) and data.get("generator") is not None:
            pins["generator"] = str(data["generator"])
    problems = []
    cache = Path(cache or os.environ.get("XROBOT_CACHE") or Path.home() / ".cache" / "xrobot")
    for tool, pin in pins.items():
        if pin is None:
            problems.append(
                tr(
                    f"{tool} is not pinned; add `{tool}: <version>`",
                    f"{tool} 没有固定版本；请添加 `{tool}: <版本>`",
                )
            )
            continue
        if not re.fullmatch(r"[0-9a-f]{40}", pin):
            continue  # 发布版本本身就是发布 / a release version is released by definition
        if offline:
            problems.append(
                tr(
                    f"{tool} pin {pin[:12]} cannot be checked offline",
                    f"离线时无法检查 {tool} 固定的 {pin[:12]}",
                )
            )
            continue
        repo = cache / (tool + ".git")
        if not repo.exists():
            git(None, "clone", "--bare", "--filter=blob:none", TOOL_REPOSITORIES[tool], str(repo))
        _fetch(repo, "origin", "+refs/heads/*:refs/heads/*")
        branches = ["dev"] if line == "dev" else ["master", "main"]
        ok = any(
            git(repo, "merge-base", "--is-ancestor", pin, "refs/heads/" + b, check=False)
            is not None
            for b in branches
        )
        if not ok:
            problems.append(
                tr(
                    f"{tool} pin {pin[:12]} is not on the tool's {branches[0]} line; pin a "
                    "release version or a merged commit",
                    f"{tool} 固定的 {pin[:12]} 不在工具的 {branches[0]} 线上；请固定发布版本或"
                    "已合并的提交",
                )
            )
    if problems:
        raise ValueError("\n".join(problems))


def write_cmake(modules_dir: Path, records: dict) -> None:
    """写出 Modules/CMakeLists.txt：模块自带 CMakeLists.txt 时 include 它，否则加 include 目录。
    Write Modules/CMakeLists.txt: include a Module's own CMakeLists.txt, else add its
    folder to the include path.
    """
    lines = ["# Generated by `xrobot setup` from xrobot.lock; do not edit or commit.", ""]
    for identity in sorted(records):
        validate_id(identity)
        folder = Path(modules_dir) / identity
        if (folder / "CMakeLists.txt").exists():
            lines.append(f'include("${{CMAKE_CURRENT_LIST_DIR}}/{identity}/CMakeLists.txt")')
        else:
            lines.append(
                f'target_include_directories(xr PUBLIC "${{CMAKE_CURRENT_LIST_DIR}}/{identity}")'
            )
    atomic_write(Path(modules_dir) / "CMakeLists.txt", "\n".join(lines) + "\n")


def _load_lock(lock_path: Path) -> dict:
    """读取并检查 xrobot.lock。
    Read and check xrobot.lock.

    Raises:
        ValueError: 格式不受支持、是旧格式，或 commit 不是 40 位。
            An unsupported or legacy format, or a commit that is not 40-hex.
    """
    lock = load_yaml(lock_path)
    entries = lock.get("modules")
    if lock.get("version") != 1 or not isinstance(entries, dict):
        raise ValueError(
            tr(
                f"{lock_path}: unsupported lock format; regenerate it with `xrobot setup --update`",
                f"{lock_path}: 不支持的 lock 格式；请用 `xrobot setup --update` 重新生成",
            )
        )
    for identity, entry in entries.items():
        validate_id(identity)
        if not isinstance(entry, dict) or "directory" in entry:
            raise ValueError(
                tr(
                    f"Legacy lock entry for {identity}; regenerate it with `xrobot setup --update`",
                    f"{identity} 是旧格式的 lock 条目；请用 `xrobot setup --update` 重新生成",
                )
            )
        if not re.fullmatch(r"[0-9a-f]{40}", str(entry.get("commit", ""))):
            raise ValueError(
                tr("Invalid locked commit for " + identity, identity + " 锁定的提交无效")
            )
    return lock


def _root_context(project: Project, roots: list[dict], context_ref: str | None) -> tuple | None:
    """modules.yaml 中 same/same-or-dev 请求跟随的分支：--context-ref 或 BSP 当前分支。
    The branch that same/same-or-dev requests of modules.yaml follow: --context-ref or the
    current branch of the BSP.

    Returns:
        ("branch"|"tag", 名字)，不在分支上时为 None。
        ("branch"|"tag", name), or None when not on a branch.
    """
    needs_parent = any(
        req["ref"] in ("same", "same-or-dev") and not req.get("context_ref") for req in roots
    )
    selected = context_ref
    if selected is None and needs_parent:
        selected = git(project.root, "symbolic-ref", "--quiet", "HEAD", check=False)
    return context(selected) if selected else None


def _load_sources(project: Project) -> SourceManager:
    """读取 BSP 的源；下载失败时附上 --offline 的提示。
    Read the Sources of the BSP; a failed download adds the --offline hint.
    """
    try:
        return SourceManager(project.sources_yaml)
    except SourceUnavailable as error:
        raise SourceUnavailable(f"{error}; {_offline_hint()}") from error


def sync_modules(
    project: Project,
    update: list[str] | None = None,
    frozen: bool = False,
    offline: bool = False,
    context_ref: str | None = None,
    release_ref: str | None = None,
) -> dict:
    """解析并检出模块，按需写 xrobot.lock，返回 lock 的内容。
    Resolve and check out the Modules, write xrobot.lock when needed, and return its content.

    Args:
        update: None 不更新，[] 更新全部，或要更新的模块 id 列表。
            None for no update, [] for all, or the ids of the Modules to update.
        frozen: 严格按 lock 检出，从不写 lock。
            Check out exactly the lock and never write it.
        offline: 不联网。
            Use no network.
        context_ref: same/same-or-dev 跟随的分支，代替 BSP 当前分支。
            The branch for same/same-or-dev to follow instead of the BSP branch.
        release_ref: 发布门禁的目标 ref。
            The target ref of the release gate.

    Raises:
        ValueError: 参数冲突、lock 与请求不符（--frozen/--offline）、解析或检出失败。
            Conflicting options, a lock that does not match the requests (--frozen or
            --offline), or a failed resolution or checkout.
    """
    if update is not None and (frozen or offline):
        raise ValueError(
            tr(
                "--update cannot be combined with --frozen or --offline",
                "--update 不能与 --frozen 或 --offline 同时使用",
            )
        )
    roots, _ = read_modules_yaml(project.modules_yaml)
    lock_dir = project.lock.resolve().parent
    lock = _load_lock(project.lock) if project.lock.is_file() else None
    if frozen or offline:
        if lock is None:
            raise ValueError(
                tr(
                    "xrobot.lock does not exist; run `xrobot setup` once without --frozen or "
                    "--offline",
                    "xrobot.lock 不存在；请先不带 --frozen 或 --offline 运行一次 `xrobot setup`",
                )
            )
        if not _same_requests(lock.get("requests") or [], roots):
            changed = _changed_requests(lock.get("requests") or [], roots)
            raise ValueError(
                tr(
                    f"Modules/modules.yaml differs from xrobot.lock ({', '.join(changed)}); run "
                    "`xrobot setup` to update the lock",
                    f"Modules/modules.yaml 与 xrobot.lock 不一致（{'、'.join(changed)}）；"
                    "请运行 `xrobot setup` 更新 lock",
                )
            )
    if lock is not None and update is None and _same_requests(lock.get("requests") or [], roots):
        manager = (
            (lambda: _load_sources(project))
            if not offline and project.sources_yaml.is_file()
            else None
        )
        resolver = Resolver(project.modules_dir, manager, offline=offline)
        for identity, entry in lock["modules"].items():
            resolver.prepare(identity, expanded_locator(entry["repo"], lock_dir), entry["commit"])
            resolver.resolved[identity] = entry
        validate_locked_graph(resolver, roots)
        records = lock["modules"]
    else:
        manager = _load_sources(project)
        pinned = {}
        if lock is not None and update != []:
            named = set()
            for name in update or []:
                matches = [
                    k
                    for k in lock["modules"]
                    if name.casefold() in (k.casefold(), k.rsplit("/", 1)[-1].casefold())
                ]
                if len(matches) != 1:
                    raise ValueError(
                        tr(
                            f"{name} is not in xrobot.lock; `--update` takes Module ids from the "
                            "lock",
                            f"xrobot.lock 中没有 {name}；`--update` 只接受 lock 中的模块 id",
                        )
                    )
                named.add(matches[0])
            previous = {r["id"].casefold(): r for r in lock.get("requests") or []}
            changed = {
                r["id"].casefold()
                for r in roots
                if r["id"].casefold() in previous
                and _request_key(previous[r["id"].casefold()]) != _request_key(r)
            }
            pinned = {
                k: v
                for k, v in lock["modules"].items()
                if k not in named and k.casefold() not in changed
            }
        without_git = (
            context_ref is None
            and git(project.root, "rev-parse", "--is-inside-work-tree", check=False) != "true"
        )
        resolver = Resolver(
            project.modules_dir,
            manager,
            offline,
            pinned,
            locked=lock["modules"] if lock is not None else {},
            without_git=without_git,
        )
        root_context = (
            (NO_BRANCH, "") if without_git else _root_context(project, roots, context_ref)
        )
        pinned_ids = {k.casefold() for k in pinned}
        for root in roots:
            parent = context(root["context_ref"]) if root.get("context_ref") else root_context
            if (
                root["ref"] in ("same", "same-or-dev")
                and parent is None
                and root["id"].casefold() not in pinned_ids
            ):
                raise ValueError(
                    tr(
                        f"Modules/modules.yaml requests {root['id']}@{root['ref']}, which follows "
                        "the BSP branch, but the BSP checkout is not on a branch (detached HEAD); "
                        "pass --context-ref refs/heads/<branch>",
                        f"Modules/modules.yaml 请求的 {root['id']}@{root['ref']} 跟随 BSP 所在的"
                        "分支，但 BSP 的检出不在分支上（detached HEAD）；请传入 "
                        "--context-ref refs/heads/<分支>",
                    )
                )
            resolver.visit(root, parent)
        for warning in resolver.warnings:
            print(tr("warning: ", "警告：") + warning, file=sys.stderr)
        records = {}
        for identity, entry in sorted(resolver.resolved.items()):
            row = {k: v for k, v in entry.items() if k != "context"}
            for field in ("repo", "source"):
                row[field] = portable_locator(str(row[field]), lock_dir)
            records[identity] = row
    if release_ref:
        check_released(resolver, release_ref, offline)
    resolver.materialize()
    write_cmake(project.modules_dir, records)
    requests = sorted(roots, key=lambda r: r["id"].casefold())
    result = {"version": 1, "requests": requests, "modules": records}
    changed = (
        lock is None
        or not _same_requests(lock.get("requests") or [], requests)
        or {k: v for k, v in lock.items() if k != "requests"}
        != {k: v for k, v in result.items() if k != "requests"}
    )
    if changed and frozen:
        raise ValueError(
            tr(
                "internal: --frozen would change xrobot.lock",
                "内部错误：--frozen 会改动 xrobot.lock",
            )
        )
    # 普通 setup 按当前格式重写 lock（说明、按 id 排序的请求）；--frozen 从不写 lock。
    # A normal setup rewrites the lock in the current layout (notice, requests sorted
    # by id); --frozen never writes it.
    text = LOCK_NOTICE + yaml.safe_dump(result, sort_keys=False, allow_unicode=True)
    current = (
        project.lock.read_text(encoding="utf-8-sig").replace("\r\n", "\n")
        if project.lock.is_file()
        else None
    )
    if changed or (not frozen and current != text):
        atomic_write(project.lock, text)
    return result


def _request_key(req: dict) -> tuple:
    """比较请求用的键：id 不区分大小写。
    The key a request is compared by; the id ignores case.
    """
    return (req["id"].casefold(), req.get("ref"), req.get("context_ref"))


def _same_requests(before: list[dict], after: list[dict]) -> bool:
    """两组请求是否相同，不计顺序和 id 的大小写。
    Whether two request lists ask for the same, whatever their order and id case.
    """
    return sorted(map(_request_key, before)) == sorted(map(_request_key, after))


def _changed_requests(before: list[dict], after: list[dict]) -> list[str]:
    """两组请求的差异：+新增、-删除、~修改。
    The differences between two request lists: +added, -removed, ~changed.
    """
    old = {r["id"].casefold(): r for r in before}
    new = {r["id"].casefold(): r for r in after}
    changed = [f"+{new[i]['id']}" for i in new if i not in old]
    changed += [f"-{old[i]['id']}" for i in old if i not in new]
    changed += [
        f"~{new[i]['id']}" for i in new if i in old and _request_key(old[i]) != _request_key(new[i])
    ]
    return changed or ["repeated requests"]
