"""BSP 的组成：根目录、入口源文件、应用配置，以及生成头文件的输入清单。
The layout of a BSP: its root, the entry source, the application configurations and the
input list of the generated header.

BSP 根目录是最近的含有 Modules/modules.yaml 的目录。入口是 User/ 下唯一调用
XROBOT_MAIN() 的源文件。User/ 下除 libxr_config.yaml 以外的每个 *.yaml 都是应用配置。
生成的 User/xrobot_main.hpp 不提交；它的开头（说明行之后）记录生成它的配置和读过的每个
文件，LibXR 的 CMake 据此在不运行 Python 的情况下拒绝过期的头文件。
A BSP root is the nearest directory containing Modules/modules.yaml. The entry is the one
source under User/ that calls XROBOT_MAIN(). Every *.yaml under User/ except
libxr_config.yaml is an application configuration. The generated User/xrobot_main.hpp is
not committed; after its notice line it names the configuration it was generated from and
every file the generator read, so LibXR's CMake can refuse a stale header without Python.
"""

import os
import re
import stat
import tempfile
from pathlib import Path

from xr_syntax.cpp import identifier_occurrences
from xr_syntax.i18n import tr

MODULES_YAML = Path("Modules/modules.yaml")
SOURCE_SUFFIXES = (".c", ".cc", ".cpp", ".cxx")
HEADER_LINE = re.compile(r'^// xrobot: (config|depends) "([^"]+)"$')
HEADER_NOTICE = "// Generated by `xrobot gen` or `xrobot setup`; do not edit by hand."


class ProjectError(ValueError):
    """BSP 结构上的问题：找不到根目录、入口不唯一，或选中的配置已不存在。
    A problem with the layout of a BSP: no root, not exactly one entry, or a selected
    configuration that no longer exists.
    """


def find_root(start: str | Path = ".") -> Path:
    """从 start 向上查找含有 Modules/modules.yaml 的目录。
    Find the nearest directory at or above start that contains Modules/modules.yaml.

    Raises:
        ProjectError: 一直到文件系统根都没有找到。
            None is found up to the filesystem root.
    """
    start = Path(start).resolve()
    for folder in [start] + list(start.parents):
        if (folder / MODULES_YAML).is_file():
            return folder
    raise ProjectError(
        tr(
            f"No XRobot BSP found at or above {start} (no Modules/modules.yaml); run "
            "`xrobot init` in the BSP root to create one",
            f"在 {start} 及其上层目录中找不到 XRobot BSP（没有 Modules/modules.yaml）；"
            "请在 BSP 根目录运行 `xrobot init` 创建",
        )
    )


def atomic_write(path: str | Path, text: str) -> None:
    """以 UTF-8 原子地替换文件内容；内容相同时不写，已有文件保留权限位。
    Replace a file's content atomically as UTF-8; an identical file is not rewritten and
    an existing file keeps its permission bits.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    data = text.encode("utf-8")
    if path.exists() and path.read_bytes() == data:
        return
    if path.exists():
        mode = stat.S_IMODE(path.stat().st_mode)
    else:
        umask = os.umask(0)
        os.umask(umask)
        mode = 0o666 & ~umask
    handle, temporary = tempfile.mkstemp(
        prefix=path.name + ".", suffix=".tmp", dir=str(path.parent)
    )
    try:
        with os.fdopen(handle, "wb") as stream:
            stream.write(data)
        os.chmod(temporary, mode)
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


class Project:
    """一个 BSP 的根目录和固定路径。
    The root of a BSP and its fixed paths.
    """

    def __init__(self, root: str | Path) -> None:
        """root 是 BSP 根目录；这里不检查其中是否有 Modules/modules.yaml。
        root is the BSP root; it is not checked for Modules/modules.yaml here.
        """
        self.root = Path(root).resolve()
        self.modules_dir = self.root / "Modules"
        self.modules_yaml = self.modules_dir / "modules.yaml"
        self.sources_yaml = self.modules_dir / "sources.yaml"
        self.lock = self.root / "xrobot.lock"
        self.user = self.root / "User"
        self.header = self.user / "xrobot_main.hpp"
        self.default_config = self.user / "xrobot.yaml"
        self.libxr_config = self.user / "libxr_config.yaml"

    @classmethod
    def discover(cls, start: str | Path = ".") -> "Project":
        """从 start 向上找到的 BSP。
        The BSP found at or above start.
        """
        return cls(find_root(start))

    def relative(self, path: str | Path) -> str:
        """相对 BSP 根目录的路径（/ 分隔）；在根目录外时为绝对路径。
        The path relative to the BSP root with / separators; absolute outside the root.
        """
        # abspath 只拼接字符串；Windows 上 resolve 要打开文件询问系统，只在路径经过链接时才用。
        # abspath only joins strings; on Windows resolve opens the file to ask the system, so
        # it is used only for a path that goes through a link.
        absolute = Path(os.path.abspath(path))
        if absolute.is_relative_to(self.root):
            return absolute.relative_to(self.root).as_posix()
        resolved = absolute.resolve()
        if resolved.is_relative_to(self.root):
            return resolved.relative_to(self.root).as_posix()
        return resolved.as_posix()

    def configs(self) -> list[Path]:
        """BSP 的全部应用配置，按路径排序。
        Every application configuration of the BSP, sorted by path.
        """
        if not self.user.is_dir():
            return []
        found = [p for p in self.user.rglob("*.yaml") if p.resolve() != self.libxr_config.resolve()]
        return sorted(found, key=lambda p: self.relative(p))

    def entry(self) -> Path:
        """User/ 下唯一调用 XROBOT_MAIN() 的源文件。
        The one source under User/ that calls XROBOT_MAIN().

        Raises:
            ProjectError: 没有或有多个这样的源文件。
                No such source, or several.
        """
        callers = []
        if self.user.is_dir():
            for path in sorted(self.user.rglob("*")):
                if path.suffix not in SOURCE_SUFFIXES or not path.is_file():
                    continue
                text = path.read_text(encoding="utf-8-sig", errors="surrogateescape")
                if "XROBOT_MAIN" not in text:
                    continue
                if _calls_xrobot_main(text):
                    callers.append(path)
        if not callers:
            raise ProjectError(
                tr(
                    "No source under User/ calls XROBOT_MAIN(); the entry source must "
                    "call it once after registering its hardware with XR_REGISTER",
                    "User/ 下没有源文件调用 XROBOT_MAIN()；入口源文件应在用 XR_REGISTER "
                    "登记硬件后调用它一次",
                )
            )
        if len(callers) > 1:
            names = [self.relative(p) for p in callers]
            raise ProjectError(
                tr(
                    f"Several sources under User/ call XROBOT_MAIN(): {', '.join(names)}; a BSP has exactly "
                    "one entry",
                    f"User/ 下有多个源文件调用 XROBOT_MAIN()：{'、'.join(names)}；一个 BSP 只能有一个入口",
                )
            )
        return callers[0]

    def header_lines(self, config: Path, depends: list[Path]) -> list[str]:
        """生成头文件中说明行之后的输入清单，路径相对头文件所在目录。
        The input list that follows the notice line of the generated header, with paths
        relative to the header's folder.
        """
        lines = [f'// xrobot: config "{_header_relative(config, self.header)}"']
        lines += [f'// xrobot: depends "{_header_relative(p, self.header)}"' for p in depends]
        return lines

    def header_state(self) -> dict:
        """User/xrobot_main.hpp 是否过期，与 LibXR 的 CMake 检查一致：输入不早于头文件即过期。
        Whether User/xrobot_main.hpp is stale, as LibXR's CMake check decides: an input that
        is not older than the header makes it stale.

        Returns:
            含 status（fresh、stale、missing 或 unreadable）、config、newer 和 missing 的映射。
            A mapping with status (fresh, stale, missing or unreadable), config, newer and
            missing.
        """
        state = {
            "path": self.relative(self.header),
            "status": "missing",
            "config": None,
            "newer": [],
            "missing": [],
        }
        if not self.header.is_file():
            return state
        config, depends = read_header_inputs(self.header)
        if config is None:
            state["status"] = "unreadable"
            return state
        base = self.header.parent
        state["config"] = self.relative(base / config)
        header_time = self.header.stat().st_mtime_ns
        for relative in [config] + depends:
            path = base / relative
            if not path.is_file():
                state["missing"].append(self.relative(path))
            # CMake 的 IS_NEWER_THAN 在时间相等时也为真。
            # CMake's IS_NEWER_THAN is also true for equal times.
            elif path.stat().st_mtime_ns >= header_time:
                state["newer"].append(self.relative(path))
        state["status"] = "stale" if state["newer"] or state["missing"] else "fresh"
        return state

    def header_selection(self) -> Path | None:
        """生成头文件记录的配置，不检查它是否存在；没有可读的头文件时为 None。
        The configuration the generated header names, whether or not it exists; None
        without a readable header.

        命令使用 selected_config；describe 在选中的配置已被删除时退回到这里，以便继续描述 BSP。
        Commands use selected_config; describe falls back to this when the selected
        configuration was deleted, so that it can still describe the BSP.
        """
        if not self.header.is_file():
            return None
        config, _ = read_header_inputs(self.header)
        return (self.header.parent / config).resolve() if config is not None else None

    def selected_config(self) -> Path:
        """当前选中的配置：头文件记录的那份，没有头文件时为 User/xrobot.yaml。
        The selected configuration: the one the header names, else User/xrobot.yaml.

        Raises:
            ProjectError: 头文件记录的配置已不存在；不会改用默认配置。
                The configuration the header names no longer exists; the default is not
                used instead.
        """
        chosen = self.header_selection()
        if chosen is None:
            return self.default_config
        if not chosen.is_file():
            raise ProjectError(
                tr(
                    f"{self.relative(self.header)} was generated for {self.relative(chosen)}, "
                    "which does not exist; select a configuration with `xrobot gen -c <config>`",
                    f"{self.relative(self.header)} 是为 {self.relative(chosen)} 生成的，但这份配置"
                    "已不存在；请用 `xrobot gen -c <配置>` 选择一份配置",
                )
            )
        return chosen


def _calls_xrobot_main(text: str) -> bool:
    """代码中是否调用了 XROBOT_MAIN（预处理行、注释和字面量不算）。
    Whether the code calls XROBOT_MAIN (preprocessor lines, comments and literals do not
    count).
    """
    # 不含这个词的文件不必做词法分析；User/ 下大多数源文件属于这种情况。
    # A file without the word needs no lexing; most sources under User/ are like that.
    if "XROBOT_MAIN" not in text:
        return False
    return any(o.text == "XROBOT_MAIN" and o.following == "(" for o in identifier_occurrences(text))


def _header_relative(path: str | Path, header: Path) -> str:
    """path 相对头文件所在目录的写法；在另一个 Windows 盘符上时为绝对路径。
    path relative to the header's folder; absolute on another Windows drive.
    """
    base = Path(os.path.abspath(header)).parent
    try:
        return Path(os.path.relpath(os.path.abspath(path), base)).as_posix()
    except ValueError:
        return Path(os.path.abspath(path)).as_posix()


def read_header_inputs(header: str | Path) -> tuple[str | None, list[str]]:
    """读取生成头文件的输入清单。
    Read the input list of a generated header.

    Returns:
        (配置, [依赖])，路径相对头文件所在目录；读不出时为 (None, [])。
        (config, [depends]) relative to the header's folder; (None, []) when unreadable.
    """
    config, depends = None, []
    try:
        lines = Path(header).read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError:
        return None, []
    for line in lines[1:]:
        if line == HEADER_NOTICE:
            continue
        if not line.startswith("// xrobot:"):
            break
        match = HEADER_LINE.match(line)
        if not match:
            return None, []
        kind, value = match.groups()
        if kind == "config":
            if config is not None:
                return None, []
            config = value
        else:
            depends.append(value)
    if config is None or not depends:
        return None, []
    return config, depends
