if(${PWM_SERVO})
    set(DEVICE_SERVO True PARENT_SCOPE)
    file(GLOB CUR_SOURCES "${SUB_DIR}/*.cpp")

    SUB_ADD_SRC(CUR_SOURCES)
    SUB_ADD_INC(SUB_DIR)
else()
    set(DEVICE_SERVO False PARENT_SCOPE)
endif()
