add_compile_options(-Wall -Wextra -fno-builtin -fno-exceptions -ffunction-sections -fdata-sections)
link_libraries(pthread)
set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_ASM_COMPILER clang)
