if(${SPI_BMI088})
    set(DEVICE_BMI088 True PARENT_SCOPE)

    file(GLOB CUR_SOURCES "${SUB_DIR}/*.cpp")

    SUB_ADD_SRC(CUR_SOURCES)
    SUB_ADD_INC(SUB_DIR)
else()
    set(DEVICE_BMI088 False PARENT_SCOPE)
endif()
